/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (64-bit)
 * Generated C source from "hbfoxpro\hbfoxpro.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( AELEMENT );
HB_FUNC_EXTERN( BETWEEN );
HB_FUNC_EXTERN( FILTER );
HB_FUNC_EXTERN( FOX_AT );
HB_FUNC_EXTERN( FOX___DYNCALL );
HB_FUNC_EXTERN( FSIZE );
HB_FUNC_EXTERN( ID );
HB_FUNC_EXTERN( INLIST );
HB_FUNC_EXTERN( INSMODE );
HB_FUNC_EXTERN( KEY );
HB_FUNC_EXTERN( LINENO );
HB_FUNC_EXTERN( NDX );
HB_FUNC_EXTERN( OCCURS );
HB_FUNC_EXTERN( PARAMETERS );
HB_FUNC_EXTERN( PRINTSTATUS );
HB_FUNC_EXTERN( PROGRAM );
HB_FUNC_EXTERN( RELATION );
HB_FUNC_EXTERN( SCOLS );
HB_FUNC_EXTERN( SROWS );
HB_FUNC_EXTERN( SYS );
HB_FUNC_EXTERN( VARREAD );
HB_FUNC_EXTERN( __FOX_ARRAY );
HB_FUNC_EXTERN( __FOX_SEEK );
HB_FUNC_EXTERN( __FOX_USED );
HB_FUNC( __HBEXTERN__HBFOXPRO__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBFOXPRO )
{ "AELEMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( AELEMENT )}, NULL },
{ "BETWEEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( BETWEEN )}, NULL },
{ "FILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILTER )}, NULL },
{ "FOX_AT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FOX_AT )}, NULL },
{ "FOX___DYNCALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( FOX___DYNCALL )}, NULL },
{ "FSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FSIZE )}, NULL },
{ "ID", {HB_FS_PUBLIC}, {HB_FUNCNAME( ID )}, NULL },
{ "INLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( INLIST )}, NULL },
{ "INSMODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( INSMODE )}, NULL },
{ "KEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( KEY )}, NULL },
{ "LINENO", {HB_FS_PUBLIC}, {HB_FUNCNAME( LINENO )}, NULL },
{ "NDX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NDX )}, NULL },
{ "OCCURS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OCCURS )}, NULL },
{ "PARAMETERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PARAMETERS )}, NULL },
{ "PRINTSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTSTATUS )}, NULL },
{ "PROGRAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROGRAM )}, NULL },
{ "RELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( RELATION )}, NULL },
{ "SCOLS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCOLS )}, NULL },
{ "SROWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SROWS )}, NULL },
{ "SYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SYS )}, NULL },
{ "VARREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( VARREAD )}, NULL },
{ "__FOX_ARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( __FOX_ARRAY )}, NULL },
{ "__FOX_SEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( __FOX_SEEK )}, NULL },
{ "__FOX_USED", {HB_FS_PUBLIC}, {HB_FUNCNAME( __FOX_USED )}, NULL },
{ "__HBEXTERN__HBFOXPRO__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBFOXPRO__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBFOXPRO, "hbfoxpro\\hbfoxpro.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBFOXPRO
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBFOXPRO )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBFOXPRO__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

