/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (32-bit)
 * Generated C source from "xhb\xhb.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( ALENALLOC );
HB_FUNC_EXTERN( AMERGE );
HB_FUNC_EXTERN( ANSITOWIDE );
HB_FUNC_EXTERN( ANY2STR );
HB_FUNC_EXTERN( AREMOVE );
HB_FUNC_EXTERN( ASIZEALLOC );
HB_FUNC_EXTERN( ASPLICE );
HB_FUNC_EXTERN( ATI );
HB_FUNC_EXTERN( ATSKIPSTRINGS );
HB_FUNC_EXTERN( BACKBUTTON );
HB_FUNC_EXTERN( BACKFORMBUTTON );
HB_FUNC_EXTERN( CGIPARSEVAR );
HB_FUNC_EXTERN( CREATEOBJECT );
HB_FUNC_EXTERN( CREATEOLEOBJECT );
HB_FUNC_EXTERN( CSTR );
HB_FUNC_EXTERN( CSTRTOVAL );
HB_FUNC_EXTERN( CTOT );
HB_FUNC_EXTERN( CURDIRX );
HB_FUNC_EXTERN( DATETIME );
HB_FUNC_EXTERN( DBF2TEXT );
HB_FUNC_EXTERN( DBIMPORT );
HB_FUNC_EXTERN( DBMERGE );
HB_FUNC_EXTERN( DBMODIFYSTRUCTURE );
HB_FUNC_EXTERN( DEFAULT );
HB_FUNC_EXTERN( DESTROYMUTEX );
HB_FUNC_EXTERN( DIRECTORYRECURSE );
HB_FUNC_EXTERN( DISABLEWAITLOCKS );
HB_FUNC_EXTERN( FCHARCOUNT );
HB_FUNC_EXTERN( FILEREADER );
HB_FUNC_EXTERN( FILESTATS );
HB_FUNC_EXTERN( FILEWRITER );
HB_FUNC_EXTERN( FLINECOUNT );
HB_FUNC_EXTERN( FPARSE );
HB_FUNC_EXTERN( FPARSEEX );
HB_FUNC_EXTERN( FPARSELINE );
HB_FUNC_EXTERN( FWORDCOUNT );
HB_FUNC_EXTERN( GETACTIVEOBJECT );
HB_FUNC_EXTERN( GETCURRENTTHREAD );
HB_FUNC_EXTERN( GETDEFAULTPRINTER );
HB_FUNC_EXTERN( GETPRINTERS );
HB_FUNC_EXTERN( GETREGISTRY );
HB_FUNC_EXTERN( GETSYSTEMTHREADID );
HB_FUNC_EXTERN( GETTABLE );
HB_FUNC_EXTERN( GETTHREADID );
HB_FUNC_EXTERN( GETVOLINFO );
HB_FUNC_EXTERN( GFXPRIMITIVE );
HB_FUNC_EXTERN( GFXTEXT );
HB_FUNC_EXTERN( GREEK2HTML );
HB_FUNC_EXTERN( GTGETCLIPBOARD );
HB_FUNC_EXTERN( GTGETCLIPBOARDSIZE );
HB_FUNC_EXTERN( GTPASTECLIPBOARD );
HB_FUNC_EXTERN( GTPROCESSMESSAGES );
HB_FUNC_EXTERN( GTSETCLIPBOARD );
HB_FUNC_EXTERN( HAADELAT );
HB_FUNC_EXTERN( HAAGETKEYAT );
HB_FUNC_EXTERN( HAAGETPOS );
HB_FUNC_EXTERN( HAAGETREALPOS );
HB_FUNC_EXTERN( HAAGETVALUEAT );
HB_FUNC_EXTERN( HAASETVALUEAT );
HB_FUNC_EXTERN( HALLOCATE );
HB_FUNC_EXTERN( HASH );
HB_FUNC_EXTERN( HBCONSOLELOCK );
HB_FUNC_EXTERN( HBCONSOLEUNLOCK );
HB_FUNC_EXTERN( HBFIELD );
HB_FUNC_EXTERN( HBORDER );
HB_FUNC_EXTERN( HBRECORD );
HB_FUNC_EXTERN( HBTABLE );
HB_FUNC_EXTERN( HBXML_DATAREAD );
HB_FUNC_EXTERN( HBXML_NODE_ADD_BELOW );
HB_FUNC_EXTERN( HBXML_NODE_CLONE );
HB_FUNC_EXTERN( HBXML_NODE_CLONE_TREE );
HB_FUNC_EXTERN( HBXML_NODE_INSERT_AFTER );
HB_FUNC_EXTERN( HBXML_NODE_INSERT_BEFORE );
HB_FUNC_EXTERN( HBXML_NODE_INSERT_BELOW );
HB_FUNC_EXTERN( HBXML_NODE_TO_STRING );
HB_FUNC_EXTERN( HBXML_NODE_UNLINK );
HB_FUNC_EXTERN( HBXML_NODE_WRITE );
HB_FUNC_EXTERN( HB_ARRAYBLOCK );
HB_FUNC_EXTERN( HB_ARRAYID );
HB_FUNC_EXTERN( HB_ARRAYTOSTRUCTURE );
HB_FUNC_EXTERN( HB_BACKGROUNDACTIVE );
HB_FUNC_EXTERN( HB_BACKGROUNDADD );
HB_FUNC_EXTERN( HB_BACKGROUNDDEL );
HB_FUNC_EXTERN( HB_BACKGROUNDRESET );
HB_FUNC_EXTERN( HB_BACKGROUNDRUN );
HB_FUNC_EXTERN( HB_BACKGROUNDRUNFORCED );
HB_FUNC_EXTERN( HB_BACKGROUNDTIME );
HB_FUNC_EXTERN( HB_BITISSET );
HB_FUNC_EXTERN( HB_BLDLOGMSG );
HB_FUNC_EXTERN( HB_BUILDINFO );
HB_FUNC_EXTERN( HB_CHECKSUM );
HB_FUNC_EXTERN( HB_CLOSEPROCESS );
HB_FUNC_EXTERN( HB_CLOSESTANDARDLOG );
HB_FUNC_EXTERN( HB_CMDARGARGV );
HB_FUNC_EXTERN( HB_COMPRESS );
HB_FUNC_EXTERN( HB_COMPRESSBUFLEN );
HB_FUNC_EXTERN( HB_COMPRESSERROR );
HB_FUNC_EXTERN( HB_COMPRESSERRORDESC );
HB_FUNC_EXTERN( HB_CREATELEN8 );
HB_FUNC_EXTERN( HB_CRYPT );
HB_FUNC_EXTERN( HB_CSTRUCTURE );
HB_FUNC_EXTERN( HB_CSTRUCTURECSYNTAX );
HB_FUNC_EXTERN( HB_CSTRUCTUREFROMID );
HB_FUNC_EXTERN( HB_CSTRUCTUREID );
HB_FUNC_EXTERN( HB_CTYPEARRAYID );
HB_FUNC_EXTERN( HB_DECODE );
HB_FUNC_EXTERN( HB_DECODEOREMPTY );
HB_FUNC_EXTERN( HB_DECRYPT );
HB_FUNC_EXTERN( HB_DESERIALBEGIN );
HB_FUNC_EXTERN( HB_DESERIALNEXT );
HB_FUNC_EXTERN( HB_DUMPVAR );
HB_FUNC_EXTERN( HB_EMPTYLOGFILEONOFF );
HB_FUNC_EXTERN( HB_ENUMINDEX );
HB_FUNC_EXTERN( HB_EXEC );
HB_FUNC_EXTERN( HB_FREADLINE );
HB_FUNC_EXTERN( HB_FUNCPTR );
HB_FUNC_EXTERN( HB_F_EOF );
HB_FUNC_EXTERN( HB_GETLEN8 );
HB_FUNC_EXTERN( HB_HASHADDMEMBER );
HB_FUNC_EXTERN( HB_HASHID );
HB_FUNC_EXTERN( HB_INITSTANDARDLOG );
HB_FUNC_EXTERN( HB_ISREGEXSTRING );
HB_FUNC_EXTERN( HB_ISSERVICE );
HB_FUNC_EXTERN( HB_IS_CSTRUCTURE );
HB_FUNC_EXTERN( HB_LIBDO );
HB_FUNC_EXTERN( HB_LOGCHANNEL );
HB_FUNC_EXTERN( HB_LOGCONSOLE );
HB_FUNC_EXTERN( HB_LOGDATESTAMP );
HB_FUNC_EXTERN( HB_LOGDBF );
HB_FUNC_EXTERN( HB_LOGDEBUG );
HB_FUNC_EXTERN( HB_LOGEMAIL );
HB_FUNC_EXTERN( HB_LOGFILE );
HB_FUNC_EXTERN( HB_LOGGER );
HB_FUNC_EXTERN( HB_LOGINETPORT );
HB_FUNC_EXTERN( HB_LOGSYSLOG );
HB_FUNC_EXTERN( HB_MEMBER );
HB_FUNC_EXTERN( HB_MULTITHREAD );
HB_FUNC_EXTERN( HB_MUTEXTIMEOUTLOCK );
HB_FUNC_EXTERN( HB_MUTEXTRYLOCK );
HB_FUNC_EXTERN( HB_OPENPROCESS );
HB_FUNC_EXTERN( HB_OPENSTANDARDLOG );
HB_FUNC_EXTERN( HB_OUTDEBUG );
HB_FUNC_EXTERN( HB_OUTDEBUGNAME );
HB_FUNC_EXTERN( HB_POINTER2STRING );
HB_FUNC_EXTERN( HB_POPSIGNALHANDLER );
HB_FUNC_EXTERN( HB_PUSHSIGNALHANDLER );
HB_FUNC_EXTERN( HB_QSELF );
HB_FUNC_EXTERN( HB_QWITH );
HB_FUNC_EXTERN( HB_READINI );
HB_FUNC_EXTERN( HB_READLINE );
HB_FUNC_EXTERN( HB_REGEXREPLACE );
HB_FUNC_EXTERN( HB_RESETWITH );
HB_FUNC_EXTERN( HB_SERVICEGENERATEFAULT );
HB_FUNC_EXTERN( HB_SERVICEGENERATEFPE );
HB_FUNC_EXTERN( HB_SERVICELOOP );
HB_FUNC_EXTERN( HB_SETCODEPAGE );
HB_FUNC_EXTERN( HB_SETINICOMMENT );
HB_FUNC_EXTERN( HB_SETSTANDARDLOGSTYLE );
HB_FUNC_EXTERN( HB_SIGNALDESC );
HB_FUNC_EXTERN( HB_SIZEOFCSTRUCTURE );
HB_FUNC_EXTERN( HB_STANDARDLOG );
HB_FUNC_EXTERN( HB_STANDARDLOGADD );
HB_FUNC_EXTERN( HB_STANDARDLOGNAME );
HB_FUNC_EXTERN( HB_STARTSERVICE );
HB_FUNC_EXTERN( HB_STRING2POINTER );
HB_FUNC_EXTERN( HB_STRUCTURETOARRAY );
HB_FUNC_EXTERN( HB_SYSLOGCLOSE );
HB_FUNC_EXTERN( HB_SYSLOGMESSAGE );
HB_FUNC_EXTERN( HB_SYSLOGOPEN );
HB_FUNC_EXTERN( HB_TABEXPAND );
HB_FUNC_EXTERN( HB_TOLOGFILE );
HB_FUNC_EXTERN( HB_TOLOGFILEONOFF );
HB_FUNC_EXTERN( HB_TOOUTDEBUG );
HB_FUNC_EXTERN( HB_TOOUTDEBUGONOFF );
HB_FUNC_EXTERN( HB_UNCOMPRESS );
HB_FUNC_EXTERN( HB_VMMODE );
HB_FUNC_EXTERN( HB_WITHOBJECTCOUNTER );
HB_FUNC_EXTERN( HB_WRITEINI );
HB_FUNC_EXTERN( HB_XMLERRORDESC );
HB_FUNC_EXTERN( HCLONE );
HB_FUNC_EXTERN( HCOPY );
HB_FUNC_EXTERN( HDEFAULT );
HB_FUNC_EXTERN( HDEL );
HB_FUNC_EXTERN( HDELAT );
HB_FUNC_EXTERN( HEVAL );
HB_FUNC_EXTERN( HEXTONUM );
HB_FUNC_EXTERN( HEXTOSTR );
HB_FUNC_EXTERN( HFILL );
HB_FUNC_EXTERN( HGET );
HB_FUNC_EXTERN( HGETAACOMPATIBILITY );
HB_FUNC_EXTERN( HGETAUTOADD );
HB_FUNC_EXTERN( HGETCASEMATCH );
HB_FUNC_EXTERN( HGETKEYAT );
HB_FUNC_EXTERN( HGETKEYS );
HB_FUNC_EXTERN( HGETPAIRAT );
HB_FUNC_EXTERN( HGETPARTITION );
HB_FUNC_EXTERN( HGETPOS );
HB_FUNC_EXTERN( HGETVAAPOS );
HB_FUNC_EXTERN( HGETVALUEAT );
HB_FUNC_EXTERN( HGETVALUES );
HB_FUNC_EXTERN( HHASKEY );
HB_FUNC_EXTERN( HMERGE );
HB_FUNC_EXTERN( HMS2D );
HB_FUNC_EXTERN( HOUR );
HB_FUNC_EXTERN( HSCAN );
HB_FUNC_EXTERN( HSET );
HB_FUNC_EXTERN( HSETAACOMPATIBILITY );
HB_FUNC_EXTERN( HSETAUTOADD );
HB_FUNC_EXTERN( HSETCASEMATCH );
HB_FUNC_EXTERN( HSETPARTITION );
HB_FUNC_EXTERN( HSETVALUEAT );
HB_FUNC_EXTERN( HTMLANY2STR );
HB_FUNC_EXTERN( HTMLBROWSE );
HB_FUNC_EXTERN( HTMLDECODEURL );
HB_FUNC_EXTERN( HTMLFORMNAME );
HB_FUNC_EXTERN( HTMLFORMOBJECT );
HB_FUNC_EXTERN( HTMLJSCMD );
HB_FUNC_EXTERN( HTMLLINKSTYLE );
HB_FUNC_EXTERN( HTMLPADL );
HB_FUNC_EXTERN( HTMLPADR );
HB_FUNC_EXTERN( HTMLPAGEHANDLE );
HB_FUNC_EXTERN( HTMLPAGEOBJECT );
HB_FUNC_EXTERN( I18N );
HB_FUNC_EXTERN( INETACCEPT );
HB_FUNC_EXTERN( INETADDRESS );
HB_FUNC_EXTERN( INETCLEANUP );
HB_FUNC_EXTERN( INETCLEARERROR );
HB_FUNC_EXTERN( INETCLEARPERIODCALLBACK );
HB_FUNC_EXTERN( INETCLEARTIMELIMIT );
HB_FUNC_EXTERN( INETCLEARTIMEOUT );
HB_FUNC_EXTERN( INETCLOSE );
HB_FUNC_EXTERN( INETCONNECT );
HB_FUNC_EXTERN( INETCONNECTIP );
HB_FUNC_EXTERN( INETCOUNT );
HB_FUNC_EXTERN( INETCREATE );
HB_FUNC_EXTERN( INETCRLF );
HB_FUNC_EXTERN( INETDATAREADY );
HB_FUNC_EXTERN( INETDESTROY );
HB_FUNC_EXTERN( INETDGRAM );
HB_FUNC_EXTERN( INETDGRAMBIND );
HB_FUNC_EXTERN( INETDGRAMRECV );
HB_FUNC_EXTERN( INETDGRAMSEND );
HB_FUNC_EXTERN( INETERRORCODE );
HB_FUNC_EXTERN( INETERRORDESC );
HB_FUNC_EXTERN( INETFD );
HB_FUNC_EXTERN( INETGETALIAS );
HB_FUNC_EXTERN( INETGETHOSTS );
HB_FUNC_EXTERN( INETGETPERIODCALLBACK );
HB_FUNC_EXTERN( INETGETTIMELIMIT );
HB_FUNC_EXTERN( INETGETTIMEOUT );
HB_FUNC_EXTERN( INETINIT );
HB_FUNC_EXTERN( INETISSOCKET );
HB_FUNC_EXTERN( INETPORT );
HB_FUNC_EXTERN( INETRECV );
HB_FUNC_EXTERN( INETRECVALL );
HB_FUNC_EXTERN( INETRECVENDBLOCK );
HB_FUNC_EXTERN( INETRECVLINE );
HB_FUNC_EXTERN( INETSEND );
HB_FUNC_EXTERN( INETSENDALL );
HB_FUNC_EXTERN( INETSERVER );
HB_FUNC_EXTERN( INETSETPERIODCALLBACK );
HB_FUNC_EXTERN( INETSETTIMELIMIT );
HB_FUNC_EXTERN( INETSETTIMEOUT );
HB_FUNC_EXTERN( INETSTATUS );
HB_FUNC_EXTERN( INITGREEK );
HB_FUNC_EXTERN( ISALNUM );
HB_FUNC_EXTERN( ISASCII );
HB_FUNC_EXTERN( ISCNTRL );
HB_FUNC_EXTERN( ISDIR );
HB_FUNC_EXTERN( ISDIRECTORY );
HB_FUNC_EXTERN( ISGRAPH );
HB_FUNC_EXTERN( ISLOCKED );
HB_FUNC_EXTERN( ISPOINTER );
HB_FUNC_EXTERN( ISPRINT );
HB_FUNC_EXTERN( ISPUNCT );
HB_FUNC_EXTERN( ISSAMETHREAD );
HB_FUNC_EXTERN( ISSPACE );
HB_FUNC_EXTERN( ISVALIDTHREAD );
HB_FUNC_EXTERN( ISXDIGIT );
HB_FUNC_EXTERN( JOINTHREAD );
HB_FUNC_EXTERN( JWINDOW );
HB_FUNC_EXTERN( KILLALLTHREADS );
HB_FUNC_EXTERN( KILLTHREAD );
HB_FUNC_EXTERN( LIBFREE );
HB_FUNC_EXTERN( LIBLOAD );
HB_FUNC_EXTERN( MESSAGEBOX );
HB_FUNC_EXTERN( METHODNAME );
HB_FUNC_EXTERN( MINUTE );
HB_FUNC_EXTERN( NETAPPEND );
HB_FUNC_EXTERN( NETCOMMITALL );
HB_FUNC_EXTERN( NETDBUSE );
HB_FUNC_EXTERN( NETDELETE );
HB_FUNC_EXTERN( NETERROR );
HB_FUNC_EXTERN( NETFILELOCK );
HB_FUNC_EXTERN( NETFLUSH );
HB_FUNC_EXTERN( NETFUNC );
HB_FUNC_EXTERN( NETLOCK );
HB_FUNC_EXTERN( NETOPENFILES );
HB_FUNC_EXTERN( NETRECALL );
HB_FUNC_EXTERN( NETRECLOCK );
HB_FUNC_EXTERN( NOTIFY );
HB_FUNC_EXTERN( NOTIFYALL );
HB_FUNC_EXTERN( NUMANDX );
HB_FUNC_EXTERN( NUMMIRRX );
HB_FUNC_EXTERN( NUMNOTX );
HB_FUNC_EXTERN( NUMORX );
HB_FUNC_EXTERN( NUMROLX );
HB_FUNC_EXTERN( NUMTOHEX );
HB_FUNC_EXTERN( NUMXORX );
HB_FUNC_EXTERN( OCCURS );
HB_FUNC_EXTERN( OLE2TXTERROR );
HB_FUNC_EXTERN( OLEDEFAULTARG );
HB_FUNC_EXTERN( OLEERROR );
HB_FUNC_EXTERN( OS_ISWIN2000 );
HB_FUNC_EXTERN( OS_ISWIN2000_OR_LATER );
HB_FUNC_EXTERN( OS_ISWIN2003 );
HB_FUNC_EXTERN( OS_ISWIN7 );
HB_FUNC_EXTERN( OS_ISWIN8 );
HB_FUNC_EXTERN( OS_ISWIN95 );
HB_FUNC_EXTERN( OS_ISWIN98 );
HB_FUNC_EXTERN( OS_ISWIN9X );
HB_FUNC_EXTERN( OS_ISWINME );
HB_FUNC_EXTERN( OS_ISWINNT );
HB_FUNC_EXTERN( OS_ISWINNT351 );
HB_FUNC_EXTERN( OS_ISWINNT4 );
HB_FUNC_EXTERN( OS_ISWINVISTA );
HB_FUNC_EXTERN( OS_ISWINVISTA_OR_LATER );
HB_FUNC_EXTERN( OS_ISWINXP );
HB_FUNC_EXTERN( OS_ISWINXP_OR_LATER );
HB_FUNC_EXTERN( OS_ISWTSCLIENT );
HB_FUNC_EXTERN( OS_NETREGOK );
HB_FUNC_EXTERN( OS_NETVREDIROK );
HB_FUNC_EXTERN( OS_VERSIONINFO );
HB_FUNC_EXTERN( PARSESTRING );
HB_FUNC_EXTERN( PRGEXPTOVAL );
HB_FUNC_EXTERN( PRINTEREXISTS );
HB_FUNC_EXTERN( PRINTERPORTTONAME );
HB_FUNC_EXTERN( PRINTFILERAW );
HB_FUNC_EXTERN( PUTCOUNTER );
HB_FUNC_EXTERN( QUERYREGISTRY );
HB_FUNC_EXTERN( RASCAN );
HB_FUNC_EXTERN( SCROLLFIXED );
HB_FUNC_EXTERN( SECONDSSLEEP );
HB_FUNC_EXTERN( SETCORRUPTFUNC );
HB_FUNC_EXTERN( SETDEFAULTPRINTER );
HB_FUNC_EXTERN( SETERRORFOOTER );
HB_FUNC_EXTERN( SETINKEYAFTERBLOCK );
HB_FUNC_EXTERN( SETINKEYBEFOREBLOCK );
HB_FUNC_EXTERN( SETNETDELAY );
HB_FUNC_EXTERN( SETNETMSGCOLOR );
HB_FUNC_EXTERN( SETREGISTRY );
HB_FUNC_EXTERN( SETUNHANDLEDEXCEPTIONFILTER );
HB_FUNC_EXTERN( SPRINTF );
HB_FUNC_EXTERN( STARTTHREAD );
HB_FUNC_EXTERN( STOPTHREAD );
HB_FUNC_EXTERN( STOT );
HB_FUNC_EXTERN( STRDEL );
HB_FUNC_EXTERN( STRINGTOLITERAL );
HB_FUNC_EXTERN( STRTOHEX );
HB_FUNC_EXTERN( SUBSCRIBE );
HB_FUNC_EXTERN( SUBSCRIBENOW );
HB_FUNC_EXTERN( TABLENEW );
HB_FUNC_EXTERN( TCGI );
HB_FUNC_EXTERN( TCGIFILE );
HB_FUNC_EXTERN( THREADGETCURRENT );
HB_FUNC_EXTERN( THREADGETCURRENTINTERNAL );
HB_FUNC_EXTERN( THREADSLEEP );
HB_FUNC_EXTERN( THROW );
HB_FUNC_EXTERN( THTML );
HB_FUNC_EXTERN( THTMLCONTROL );
HB_FUNC_EXTERN( THTMLFORM );
HB_FUNC_EXTERN( THTMLFRAMESET );
HB_FUNC_EXTERN( TIMEOFDAY );
HB_FUNC_EXTERN( TJSLIST );
HB_FUNC_EXTERN( TJSWINDOW );
HB_FUNC_EXTERN( TOLEAUTO );
HB_FUNC_EXTERN( TRACELOG );
HB_FUNC_EXTERN( TRPCCLIENT );
HB_FUNC_EXTERN( TRPCFUNCTION );
HB_FUNC_EXTERN( TRPCSERVECON );
HB_FUNC_EXTERN( TRPCSERVICE );
HB_FUNC_EXTERN( TSSECS );
HB_FUNC_EXTERN( TSTREAM );
HB_FUNC_EXTERN( TSTREAMFILEREADER );
HB_FUNC_EXTERN( TSTREAMFILEWRITER );
HB_FUNC_EXTERN( TTOC );
HB_FUNC_EXTERN( TTOD );
HB_FUNC_EXTERN( TTOS );
HB_FUNC_EXTERN( TXMLDOCUMENT );
HB_FUNC_EXTERN( TXMLITERATOR );
HB_FUNC_EXTERN( TXMLITERATORREGEX );
HB_FUNC_EXTERN( TXMLITERATORSCAN );
HB_FUNC_EXTERN( TXMLNODE );
HB_FUNC_EXTERN( VALTOARRAY );
HB_FUNC_EXTERN( VALTOBLOCK );
HB_FUNC_EXTERN( VALTOCHARACTER );
HB_FUNC_EXTERN( VALTODATE );
HB_FUNC_EXTERN( VALTOHASH );
HB_FUNC_EXTERN( VALTOLOGICAL );
HB_FUNC_EXTERN( VALTONUMBER );
HB_FUNC_EXTERN( VALTOOBJECT );
HB_FUNC_EXTERN( VALTOPRG );
HB_FUNC_EXTERN( VALTOPRGEXP );
HB_FUNC_EXTERN( VALTOTYPE );
HB_FUNC_EXTERN( WAITFORTHREADS );
HB_FUNC_EXTERN( WIDETOANSI );
HB_FUNC_EXTERN( WILDMATCH );
HB_FUNC_EXTERN( WIN32BMP );
HB_FUNC_EXTERN( WIN32PRN );
HB_FUNC_EXTERN( XHBEDITOR );
HB_FUNC_EXTERN( XHB_ADEL );
HB_FUNC_EXTERN( XHB_AINS );
HB_FUNC_EXTERN( XHB_ALLTRIM );
HB_FUNC_EXTERN( XHB_BITAND );
HB_FUNC_EXTERN( XHB_BITOR );
HB_FUNC_EXTERN( XHB_BITXOR );
HB_FUNC_EXTERN( XHB_COPYFILE );
HB_FUNC_EXTERN( XHB_DEC );
HB_FUNC_EXTERN( XHB_DIV );
HB_FUNC_EXTERN( XHB_EEQUAL );
HB_FUNC_EXTERN( XHB_EQUAL );
HB_FUNC_EXTERN( XHB_ERRORLOG );
HB_FUNC_EXTERN( XHB_ERRORNEW );
HB_FUNC_EXTERN( XHB_ERRORSYS );
HB_FUNC_EXTERN( XHB_GREATER );
HB_FUNC_EXTERN( XHB_GREATEREQ );
HB_FUNC_EXTERN( XHB_HASHERROR );
HB_FUNC_EXTERN( XHB_INC );
HB_FUNC_EXTERN( XHB_INCLUDE );
HB_FUNC_EXTERN( XHB_INDEX );
HB_FUNC_EXTERN( XHB_INKEY );
HB_FUNC_EXTERN( XHB_KEYTRANS );
HB_FUNC_EXTERN( XHB_LESS );
HB_FUNC_EXTERN( XHB_LESSEQ );
HB_FUNC_EXTERN( XHB_LIB );
HB_FUNC_EXTERN( XHB_MEMOEDIT );
HB_FUNC_EXTERN( XHB_MEMOWRIT );
HB_FUNC_EXTERN( XHB_MINUS );
HB_FUNC_EXTERN( XHB_MOD );
HB_FUNC_EXTERN( XHB_MULT );
HB_FUNC_EXTERN( XHB_NETNAME );
HB_FUNC_EXTERN( XHB_NOTEQUAL );
HB_FUNC_EXTERN( XHB_PLUS );
HB_FUNC_EXTERN( XHB_POW );
HB_FUNC_EXTERN( XHB_RESTSCREEN );
HB_FUNC_EXTERN( XHB_RTRIM );
HB_FUNC_EXTERN( XHB_SAVESCREEN );
HB_FUNC_EXTERN( XHB_SETTRACE );
HB_FUNC_EXTERN( XHB_SETTRACEFILE );
HB_FUNC_EXTERN( XHB_SETTRACESTACK );
HB_FUNC_EXTERN( XHB_TMEMOEDITOR );
HB_FUNC_EXTERN( XHB_TRIM );
HB_FUNC_EXTERN( XHB__KEYBOARD );
HB_FUNC_EXTERN( XISPRINTER );
HB_FUNC_EXTERN( _ARRAY );
HB_FUNC_EXTERN( _BLOCK );
HB_FUNC_EXTERN( _CHARACTER );
HB_FUNC_EXTERN( _HASH );
HB_FUNC_EXTERN( _NUMERIC );
HB_FUNC_EXTERN( __ACTIVESTRUCTURE );
HB_FUNC_EXTERN( __CSTR_COPYTO );
HB_FUNC_EXTERN( __ERRORBLOCK );
HB_FUNC_EXTERN( __INIT_LONGLONGS );
HB_FUNC_EXTERN( __MINIMALERRORHANDLER );
HB_FUNC_EXTERN( __MVSYMBOLINFO );
HB_FUNC_EXTERN( __OLEPDISP );
HB_FUNC_EXTERN( __OUTDEBUG );
HB_FUNC_EXTERN( __SENDRAWMSG );
HB_FUNC( __HBEXTERN__XHB__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_XHB )
{ "ALENALLOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALENALLOC )}, NULL },
{ "AMERGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( AMERGE )}, NULL },
{ "ANSITOWIDE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ANSITOWIDE )}, NULL },
{ "ANY2STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ANY2STR )}, NULL },
{ "AREMOVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( AREMOVE )}, NULL },
{ "ASIZEALLOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASIZEALLOC )}, NULL },
{ "ASPLICE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASPLICE )}, NULL },
{ "ATI", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATI )}, NULL },
{ "ATSKIPSTRINGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATSKIPSTRINGS )}, NULL },
{ "BACKBUTTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( BACKBUTTON )}, NULL },
{ "BACKFORMBUTTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( BACKFORMBUTTON )}, NULL },
{ "CGIPARSEVAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CGIPARSEVAR )}, NULL },
{ "CREATEOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CREATEOBJECT )}, NULL },
{ "CREATEOLEOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CREATEOLEOBJECT )}, NULL },
{ "CSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSTR )}, NULL },
{ "CSTRTOVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSTRTOVAL )}, NULL },
{ "CTOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOT )}, NULL },
{ "CURDIRX", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURDIRX )}, NULL },
{ "DATETIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( DATETIME )}, NULL },
{ "DBF2TEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBF2TEXT )}, NULL },
{ "DBIMPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBIMPORT )}, NULL },
{ "DBMERGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBMERGE )}, NULL },
{ "DBMODIFYSTRUCTURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBMODIFYSTRUCTURE )}, NULL },
{ "DEFAULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DEFAULT )}, NULL },
{ "DESTROYMUTEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DESTROYMUTEX )}, NULL },
{ "DIRECTORYRECURSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DIRECTORYRECURSE )}, NULL },
{ "DISABLEWAITLOCKS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DISABLEWAITLOCKS )}, NULL },
{ "FCHARCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FCHARCOUNT )}, NULL },
{ "FILEREADER", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEREADER )}, NULL },
{ "FILESTATS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILESTATS )}, NULL },
{ "FILEWRITER", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEWRITER )}, NULL },
{ "FLINECOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FLINECOUNT )}, NULL },
{ "FPARSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FPARSE )}, NULL },
{ "FPARSEEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( FPARSEEX )}, NULL },
{ "FPARSELINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FPARSELINE )}, NULL },
{ "FWORDCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FWORDCOUNT )}, NULL },
{ "GETACTIVEOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETACTIVEOBJECT )}, NULL },
{ "GETCURRENTTHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETCURRENTTHREAD )}, NULL },
{ "GETDEFAULTPRINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETDEFAULTPRINTER )}, NULL },
{ "GETPRINTERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETPRINTERS )}, NULL },
{ "GETREGISTRY", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETREGISTRY )}, NULL },
{ "GETSYSTEMTHREADID", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETSYSTEMTHREADID )}, NULL },
{ "GETTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETTABLE )}, NULL },
{ "GETTHREADID", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETTHREADID )}, NULL },
{ "GETVOLINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETVOLINFO )}, NULL },
{ "GFXPRIMITIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( GFXPRIMITIVE )}, NULL },
{ "GFXTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( GFXTEXT )}, NULL },
{ "GREEK2HTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( GREEK2HTML )}, NULL },
{ "GTGETCLIPBOARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( GTGETCLIPBOARD )}, NULL },
{ "GTGETCLIPBOARDSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( GTGETCLIPBOARDSIZE )}, NULL },
{ "GTPASTECLIPBOARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( GTPASTECLIPBOARD )}, NULL },
{ "GTPROCESSMESSAGES", {HB_FS_PUBLIC}, {HB_FUNCNAME( GTPROCESSMESSAGES )}, NULL },
{ "GTSETCLIPBOARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( GTSETCLIPBOARD )}, NULL },
{ "HAADELAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HAADELAT )}, NULL },
{ "HAAGETKEYAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HAAGETKEYAT )}, NULL },
{ "HAAGETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HAAGETPOS )}, NULL },
{ "HAAGETREALPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HAAGETREALPOS )}, NULL },
{ "HAAGETVALUEAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HAAGETVALUEAT )}, NULL },
{ "HAASETVALUEAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HAASETVALUEAT )}, NULL },
{ "HALLOCATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HALLOCATE )}, NULL },
{ "HASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HASH )}, NULL },
{ "HBCONSOLELOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCONSOLELOCK )}, NULL },
{ "HBCONSOLEUNLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCONSOLEUNLOCK )}, NULL },
{ "HBFIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBFIELD )}, NULL },
{ "HBORDER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBORDER )}, NULL },
{ "HBRECORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBRECORD )}, NULL },
{ "HBTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBTABLE )}, NULL },
{ "HBXML_DATAREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_DATAREAD )}, NULL },
{ "HBXML_NODE_ADD_BELOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_ADD_BELOW )}, NULL },
{ "HBXML_NODE_CLONE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_CLONE )}, NULL },
{ "HBXML_NODE_CLONE_TREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_CLONE_TREE )}, NULL },
{ "HBXML_NODE_INSERT_AFTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_INSERT_AFTER )}, NULL },
{ "HBXML_NODE_INSERT_BEFORE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_INSERT_BEFORE )}, NULL },
{ "HBXML_NODE_INSERT_BELOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_INSERT_BELOW )}, NULL },
{ "HBXML_NODE_TO_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_TO_STRING )}, NULL },
{ "HBXML_NODE_UNLINK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_UNLINK )}, NULL },
{ "HBXML_NODE_WRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBXML_NODE_WRITE )}, NULL },
{ "HB_ARRAYBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ARRAYBLOCK )}, NULL },
{ "HB_ARRAYID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ARRAYID )}, NULL },
{ "HB_ARRAYTOSTRUCTURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ARRAYTOSTRUCTURE )}, NULL },
{ "HB_BACKGROUNDACTIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDACTIVE )}, NULL },
{ "HB_BACKGROUNDADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDADD )}, NULL },
{ "HB_BACKGROUNDDEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDDEL )}, NULL },
{ "HB_BACKGROUNDRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDRESET )}, NULL },
{ "HB_BACKGROUNDRUN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDRUN )}, NULL },
{ "HB_BACKGROUNDRUNFORCED", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDRUNFORCED )}, NULL },
{ "HB_BACKGROUNDTIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BACKGROUNDTIME )}, NULL },
{ "HB_BITISSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BITISSET )}, NULL },
{ "HB_BLDLOGMSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BLDLOGMSG )}, NULL },
{ "HB_BUILDINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BUILDINFO )}, NULL },
{ "HB_CHECKSUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CHECKSUM )}, NULL },
{ "HB_CLOSEPROCESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CLOSEPROCESS )}, NULL },
{ "HB_CLOSESTANDARDLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CLOSESTANDARDLOG )}, NULL },
{ "HB_CMDARGARGV", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CMDARGARGV )}, NULL },
{ "HB_COMPRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_COMPRESS )}, NULL },
{ "HB_COMPRESSBUFLEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_COMPRESSBUFLEN )}, NULL },
{ "HB_COMPRESSERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_COMPRESSERROR )}, NULL },
{ "HB_COMPRESSERRORDESC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_COMPRESSERRORDESC )}, NULL },
{ "HB_CREATELEN8", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CREATELEN8 )}, NULL },
{ "HB_CRYPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CRYPT )}, NULL },
{ "HB_CSTRUCTURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CSTRUCTURE )}, NULL },
{ "HB_CSTRUCTURECSYNTAX", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CSTRUCTURECSYNTAX )}, NULL },
{ "HB_CSTRUCTUREFROMID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CSTRUCTUREFROMID )}, NULL },
{ "HB_CSTRUCTUREID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CSTRUCTUREID )}, NULL },
{ "HB_CTYPEARRAYID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_CTYPEARRAYID )}, NULL },
{ "HB_DECODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_DECODE )}, NULL },
{ "HB_DECODEOREMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_DECODEOREMPTY )}, NULL },
{ "HB_DECRYPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_DECRYPT )}, NULL },
{ "HB_DESERIALBEGIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_DESERIALBEGIN )}, NULL },
{ "HB_DESERIALNEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_DESERIALNEXT )}, NULL },
{ "HB_DUMPVAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_DUMPVAR )}, NULL },
{ "HB_EMPTYLOGFILEONOFF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_EMPTYLOGFILEONOFF )}, NULL },
{ "HB_ENUMINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ENUMINDEX )}, NULL },
{ "HB_EXEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_EXEC )}, NULL },
{ "HB_FREADLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_FREADLINE )}, NULL },
{ "HB_FUNCPTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_FUNCPTR )}, NULL },
{ "HB_F_EOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_F_EOF )}, NULL },
{ "HB_GETLEN8", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_GETLEN8 )}, NULL },
{ "HB_HASHADDMEMBER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_HASHADDMEMBER )}, NULL },
{ "HB_HASHID", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_HASHID )}, NULL },
{ "HB_INITSTANDARDLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_INITSTANDARDLOG )}, NULL },
{ "HB_ISREGEXSTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISREGEXSTRING )}, NULL },
{ "HB_ISSERVICE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ISSERVICE )}, NULL },
{ "HB_IS_CSTRUCTURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_IS_CSTRUCTURE )}, NULL },
{ "HB_LIBDO", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LIBDO )}, NULL },
{ "HB_LOGCHANNEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGCHANNEL )}, NULL },
{ "HB_LOGCONSOLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGCONSOLE )}, NULL },
{ "HB_LOGDATESTAMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGDATESTAMP )}, NULL },
{ "HB_LOGDBF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGDBF )}, NULL },
{ "HB_LOGDEBUG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGDEBUG )}, NULL },
{ "HB_LOGEMAIL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGEMAIL )}, NULL },
{ "HB_LOGFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGFILE )}, NULL },
{ "HB_LOGGER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGGER )}, NULL },
{ "HB_LOGINETPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGINETPORT )}, NULL },
{ "HB_LOGSYSLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LOGSYSLOG )}, NULL },
{ "HB_MEMBER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_MEMBER )}, NULL },
{ "HB_MULTITHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_MULTITHREAD )}, NULL },
{ "HB_MUTEXTIMEOUTLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_MUTEXTIMEOUTLOCK )}, NULL },
{ "HB_MUTEXTRYLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_MUTEXTRYLOCK )}, NULL },
{ "HB_OPENPROCESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_OPENPROCESS )}, NULL },
{ "HB_OPENSTANDARDLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_OPENSTANDARDLOG )}, NULL },
{ "HB_OUTDEBUG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_OUTDEBUG )}, NULL },
{ "HB_OUTDEBUGNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_OUTDEBUGNAME )}, NULL },
{ "HB_POINTER2STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_POINTER2STRING )}, NULL },
{ "HB_POPSIGNALHANDLER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_POPSIGNALHANDLER )}, NULL },
{ "HB_PUSHSIGNALHANDLER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_PUSHSIGNALHANDLER )}, NULL },
{ "HB_QSELF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_QSELF )}, NULL },
{ "HB_QWITH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_QWITH )}, NULL },
{ "HB_READINI", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_READINI )}, NULL },
{ "HB_READLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_READLINE )}, NULL },
{ "HB_REGEXREPLACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_REGEXREPLACE )}, NULL },
{ "HB_RESETWITH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_RESETWITH )}, NULL },
{ "HB_SERVICEGENERATEFAULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SERVICEGENERATEFAULT )}, NULL },
{ "HB_SERVICEGENERATEFPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SERVICEGENERATEFPE )}, NULL },
{ "HB_SERVICELOOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SERVICELOOP )}, NULL },
{ "HB_SETCODEPAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SETCODEPAGE )}, NULL },
{ "HB_SETINICOMMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SETINICOMMENT )}, NULL },
{ "HB_SETSTANDARDLOGSTYLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SETSTANDARDLOGSTYLE )}, NULL },
{ "HB_SIGNALDESC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SIGNALDESC )}, NULL },
{ "HB_SIZEOFCSTRUCTURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SIZEOFCSTRUCTURE )}, NULL },
{ "HB_STANDARDLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_STANDARDLOG )}, NULL },
{ "HB_STANDARDLOGADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_STANDARDLOGADD )}, NULL },
{ "HB_STANDARDLOGNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_STANDARDLOGNAME )}, NULL },
{ "HB_STARTSERVICE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_STARTSERVICE )}, NULL },
{ "HB_STRING2POINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_STRING2POINTER )}, NULL },
{ "HB_STRUCTURETOARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_STRUCTURETOARRAY )}, NULL },
{ "HB_SYSLOGCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SYSLOGCLOSE )}, NULL },
{ "HB_SYSLOGMESSAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SYSLOGMESSAGE )}, NULL },
{ "HB_SYSLOGOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SYSLOGOPEN )}, NULL },
{ "HB_TABEXPAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_TABEXPAND )}, NULL },
{ "HB_TOLOGFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_TOLOGFILE )}, NULL },
{ "HB_TOLOGFILEONOFF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_TOLOGFILEONOFF )}, NULL },
{ "HB_TOOUTDEBUG", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_TOOUTDEBUG )}, NULL },
{ "HB_TOOUTDEBUGONOFF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_TOOUTDEBUGONOFF )}, NULL },
{ "HB_UNCOMPRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNCOMPRESS )}, NULL },
{ "HB_VMMODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_VMMODE )}, NULL },
{ "HB_WITHOBJECTCOUNTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_WITHOBJECTCOUNTER )}, NULL },
{ "HB_WRITEINI", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_WRITEINI )}, NULL },
{ "HB_XMLERRORDESC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_XMLERRORDESC )}, NULL },
{ "HCLONE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HCLONE )}, NULL },
{ "HCOPY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HCOPY )}, NULL },
{ "HDEFAULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HDEFAULT )}, NULL },
{ "HDEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HDEL )}, NULL },
{ "HDELAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HDELAT )}, NULL },
{ "HEVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HEVAL )}, NULL },
{ "HEXTONUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( HEXTONUM )}, NULL },
{ "HEXTOSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HEXTOSTR )}, NULL },
{ "HFILL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HFILL )}, NULL },
{ "HGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGET )}, NULL },
{ "HGETAACOMPATIBILITY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETAACOMPATIBILITY )}, NULL },
{ "HGETAUTOADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETAUTOADD )}, NULL },
{ "HGETCASEMATCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETCASEMATCH )}, NULL },
{ "HGETKEYAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETKEYAT )}, NULL },
{ "HGETKEYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETKEYS )}, NULL },
{ "HGETPAIRAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETPAIRAT )}, NULL },
{ "HGETPARTITION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETPARTITION )}, NULL },
{ "HGETPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETPOS )}, NULL },
{ "HGETVAAPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETVAAPOS )}, NULL },
{ "HGETVALUEAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETVALUEAT )}, NULL },
{ "HGETVALUES", {HB_FS_PUBLIC}, {HB_FUNCNAME( HGETVALUES )}, NULL },
{ "HHASKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HHASKEY )}, NULL },
{ "HMERGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HMERGE )}, NULL },
{ "HMS2D", {HB_FS_PUBLIC}, {HB_FUNCNAME( HMS2D )}, NULL },
{ "HOUR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HOUR )}, NULL },
{ "HSCAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSCAN )}, NULL },
{ "HSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSET )}, NULL },
{ "HSETAACOMPATIBILITY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSETAACOMPATIBILITY )}, NULL },
{ "HSETAUTOADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSETAUTOADD )}, NULL },
{ "HSETCASEMATCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSETCASEMATCH )}, NULL },
{ "HSETPARTITION", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSETPARTITION )}, NULL },
{ "HSETVALUEAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HSETVALUEAT )}, NULL },
{ "HTMLANY2STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLANY2STR )}, NULL },
{ "HTMLBROWSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLBROWSE )}, NULL },
{ "HTMLDECODEURL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLDECODEURL )}, NULL },
{ "HTMLFORMNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLFORMNAME )}, NULL },
{ "HTMLFORMOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLFORMOBJECT )}, NULL },
{ "HTMLJSCMD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLJSCMD )}, NULL },
{ "HTMLLINKSTYLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLLINKSTYLE )}, NULL },
{ "HTMLPADL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLPADL )}, NULL },
{ "HTMLPADR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLPADR )}, NULL },
{ "HTMLPAGEHANDLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLPAGEHANDLE )}, NULL },
{ "HTMLPAGEOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HTMLPAGEOBJECT )}, NULL },
{ "I18N", {HB_FS_PUBLIC}, {HB_FUNCNAME( I18N )}, NULL },
{ "INETACCEPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETACCEPT )}, NULL },
{ "INETADDRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETADDRESS )}, NULL },
{ "INETCLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCLEANUP )}, NULL },
{ "INETCLEARERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCLEARERROR )}, NULL },
{ "INETCLEARPERIODCALLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCLEARPERIODCALLBACK )}, NULL },
{ "INETCLEARTIMELIMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCLEARTIMELIMIT )}, NULL },
{ "INETCLEARTIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCLEARTIMEOUT )}, NULL },
{ "INETCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCLOSE )}, NULL },
{ "INETCONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCONNECT )}, NULL },
{ "INETCONNECTIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCONNECTIP )}, NULL },
{ "INETCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCOUNT )}, NULL },
{ "INETCREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCREATE )}, NULL },
{ "INETCRLF", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETCRLF )}, NULL },
{ "INETDATAREADY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETDATAREADY )}, NULL },
{ "INETDESTROY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETDESTROY )}, NULL },
{ "INETDGRAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETDGRAM )}, NULL },
{ "INETDGRAMBIND", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETDGRAMBIND )}, NULL },
{ "INETDGRAMRECV", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETDGRAMRECV )}, NULL },
{ "INETDGRAMSEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETDGRAMSEND )}, NULL },
{ "INETERRORCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETERRORCODE )}, NULL },
{ "INETERRORDESC", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETERRORDESC )}, NULL },
{ "INETFD", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETFD )}, NULL },
{ "INETGETALIAS", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETGETALIAS )}, NULL },
{ "INETGETHOSTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETGETHOSTS )}, NULL },
{ "INETGETPERIODCALLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETGETPERIODCALLBACK )}, NULL },
{ "INETGETTIMELIMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETGETTIMELIMIT )}, NULL },
{ "INETGETTIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETGETTIMEOUT )}, NULL },
{ "INETINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETINIT )}, NULL },
{ "INETISSOCKET", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETISSOCKET )}, NULL },
{ "INETPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETPORT )}, NULL },
{ "INETRECV", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETRECV )}, NULL },
{ "INETRECVALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETRECVALL )}, NULL },
{ "INETRECVENDBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETRECVENDBLOCK )}, NULL },
{ "INETRECVLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETRECVLINE )}, NULL },
{ "INETSEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSEND )}, NULL },
{ "INETSENDALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSENDALL )}, NULL },
{ "INETSERVER", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSERVER )}, NULL },
{ "INETSETPERIODCALLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSETPERIODCALLBACK )}, NULL },
{ "INETSETTIMELIMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSETTIMELIMIT )}, NULL },
{ "INETSETTIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSETTIMEOUT )}, NULL },
{ "INETSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( INETSTATUS )}, NULL },
{ "INITGREEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( INITGREEK )}, NULL },
{ "ISALNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISALNUM )}, NULL },
{ "ISASCII", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISASCII )}, NULL },
{ "ISCNTRL", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISCNTRL )}, NULL },
{ "ISDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISDIR )}, NULL },
{ "ISDIRECTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISDIRECTORY )}, NULL },
{ "ISGRAPH", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISGRAPH )}, NULL },
{ "ISLOCKED", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISLOCKED )}, NULL },
{ "ISPOINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISPOINTER )}, NULL },
{ "ISPRINT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISPRINT )}, NULL },
{ "ISPUNCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISPUNCT )}, NULL },
{ "ISSAMETHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISSAMETHREAD )}, NULL },
{ "ISSPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISSPACE )}, NULL },
{ "ISVALIDTHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISVALIDTHREAD )}, NULL },
{ "ISXDIGIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISXDIGIT )}, NULL },
{ "JOINTHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( JOINTHREAD )}, NULL },
{ "JWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( JWINDOW )}, NULL },
{ "KILLALLTHREADS", {HB_FS_PUBLIC}, {HB_FUNCNAME( KILLALLTHREADS )}, NULL },
{ "KILLTHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( KILLTHREAD )}, NULL },
{ "LIBFREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( LIBFREE )}, NULL },
{ "LIBLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( LIBLOAD )}, NULL },
{ "MESSAGEBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( MESSAGEBOX )}, NULL },
{ "METHODNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( METHODNAME )}, NULL },
{ "MINUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MINUTE )}, NULL },
{ "NETAPPEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETAPPEND )}, NULL },
{ "NETCOMMITALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETCOMMITALL )}, NULL },
{ "NETDBUSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETDBUSE )}, NULL },
{ "NETDELETE", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETDELETE )}, NULL },
{ "NETERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETERROR )}, NULL },
{ "NETFILELOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETFILELOCK )}, NULL },
{ "NETFLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETFLUSH )}, NULL },
{ "NETFUNC", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETFUNC )}, NULL },
{ "NETLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETLOCK )}, NULL },
{ "NETOPENFILES", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETOPENFILES )}, NULL },
{ "NETRECALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETRECALL )}, NULL },
{ "NETRECLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETRECLOCK )}, NULL },
{ "NOTIFY", {HB_FS_PUBLIC}, {HB_FUNCNAME( NOTIFY )}, NULL },
{ "NOTIFYALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NOTIFYALL )}, NULL },
{ "NUMANDX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMANDX )}, NULL },
{ "NUMMIRRX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMMIRRX )}, NULL },
{ "NUMNOTX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMNOTX )}, NULL },
{ "NUMORX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMORX )}, NULL },
{ "NUMROLX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMROLX )}, NULL },
{ "NUMTOHEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMTOHEX )}, NULL },
{ "NUMXORX", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMXORX )}, NULL },
{ "OCCURS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OCCURS )}, NULL },
{ "OLE2TXTERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( OLE2TXTERROR )}, NULL },
{ "OLEDEFAULTARG", {HB_FS_PUBLIC}, {HB_FUNCNAME( OLEDEFAULTARG )}, NULL },
{ "OLEERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( OLEERROR )}, NULL },
{ "OS_ISWIN2000", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN2000 )}, NULL },
{ "OS_ISWIN2000_OR_LATER", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN2000_OR_LATER )}, NULL },
{ "OS_ISWIN2003", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN2003 )}, NULL },
{ "OS_ISWIN7", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN7 )}, NULL },
{ "OS_ISWIN8", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN8 )}, NULL },
{ "OS_ISWIN95", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN95 )}, NULL },
{ "OS_ISWIN98", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN98 )}, NULL },
{ "OS_ISWIN9X", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWIN9X )}, NULL },
{ "OS_ISWINME", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINME )}, NULL },
{ "OS_ISWINNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINNT )}, NULL },
{ "OS_ISWINNT351", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINNT351 )}, NULL },
{ "OS_ISWINNT4", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINNT4 )}, NULL },
{ "OS_ISWINVISTA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINVISTA )}, NULL },
{ "OS_ISWINVISTA_OR_LATER", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINVISTA_OR_LATER )}, NULL },
{ "OS_ISWINXP", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINXP )}, NULL },
{ "OS_ISWINXP_OR_LATER", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWINXP_OR_LATER )}, NULL },
{ "OS_ISWTSCLIENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_ISWTSCLIENT )}, NULL },
{ "OS_NETREGOK", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_NETREGOK )}, NULL },
{ "OS_NETVREDIROK", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_NETVREDIROK )}, NULL },
{ "OS_VERSIONINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( OS_VERSIONINFO )}, NULL },
{ "PARSESTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( PARSESTRING )}, NULL },
{ "PRGEXPTOVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRGEXPTOVAL )}, NULL },
{ "PRINTEREXISTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTEREXISTS )}, NULL },
{ "PRINTERPORTTONAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTERPORTTONAME )}, NULL },
{ "PRINTFILERAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTFILERAW )}, NULL },
{ "PUTCOUNTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( PUTCOUNTER )}, NULL },
{ "QUERYREGISTRY", {HB_FS_PUBLIC}, {HB_FUNCNAME( QUERYREGISTRY )}, NULL },
{ "RASCAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( RASCAN )}, NULL },
{ "SCROLLFIXED", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCROLLFIXED )}, NULL },
{ "SECONDSSLEEP", {HB_FS_PUBLIC}, {HB_FUNCNAME( SECONDSSLEEP )}, NULL },
{ "SETCORRUPTFUNC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCORRUPTFUNC )}, NULL },
{ "SETDEFAULTPRINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETDEFAULTPRINTER )}, NULL },
{ "SETERRORFOOTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETERRORFOOTER )}, NULL },
{ "SETINKEYAFTERBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETINKEYAFTERBLOCK )}, NULL },
{ "SETINKEYBEFOREBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETINKEYBEFOREBLOCK )}, NULL },
{ "SETNETDELAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETNETDELAY )}, NULL },
{ "SETNETMSGCOLOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETNETMSGCOLOR )}, NULL },
{ "SETREGISTRY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETREGISTRY )}, NULL },
{ "SETUNHANDLEDEXCEPTIONFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETUNHANDLEDEXCEPTIONFILTER )}, NULL },
{ "SPRINTF", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPRINTF )}, NULL },
{ "STARTTHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( STARTTHREAD )}, NULL },
{ "STOPTHREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( STOPTHREAD )}, NULL },
{ "STOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( STOT )}, NULL },
{ "STRDEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRDEL )}, NULL },
{ "STRINGTOLITERAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRINGTOLITERAL )}, NULL },
{ "STRTOHEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRTOHEX )}, NULL },
{ "SUBSCRIBE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSCRIBE )}, NULL },
{ "SUBSCRIBENOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSCRIBENOW )}, NULL },
{ "TABLENEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( TABLENEW )}, NULL },
{ "TCGI", {HB_FS_PUBLIC}, {HB_FUNCNAME( TCGI )}, NULL },
{ "TCGIFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( TCGIFILE )}, NULL },
{ "THREADGETCURRENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADGETCURRENT )}, NULL },
{ "THREADGETCURRENTINTERNAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADGETCURRENTINTERNAL )}, NULL },
{ "THREADSLEEP", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADSLEEP )}, NULL },
{ "THROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( THROW )}, NULL },
{ "THTML", {HB_FS_PUBLIC}, {HB_FUNCNAME( THTML )}, NULL },
{ "THTMLCONTROL", {HB_FS_PUBLIC}, {HB_FUNCNAME( THTMLCONTROL )}, NULL },
{ "THTMLFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( THTMLFORM )}, NULL },
{ "THTMLFRAMESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( THTMLFRAMESET )}, NULL },
{ "TIMEOFDAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( TIMEOFDAY )}, NULL },
{ "TJSLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( TJSLIST )}, NULL },
{ "TJSWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( TJSWINDOW )}, NULL },
{ "TOLEAUTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOLEAUTO )}, NULL },
{ "TRACELOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRACELOG )}, NULL },
{ "TRPCCLIENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRPCCLIENT )}, NULL },
{ "TRPCFUNCTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRPCFUNCTION )}, NULL },
{ "TRPCSERVECON", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRPCSERVECON )}, NULL },
{ "TRPCSERVICE", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRPCSERVICE )}, NULL },
{ "TSSECS", {HB_FS_PUBLIC}, {HB_FUNCNAME( TSSECS )}, NULL },
{ "TSTREAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TSTREAM )}, NULL },
{ "TSTREAMFILEREADER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TSTREAMFILEREADER )}, NULL },
{ "TSTREAMFILEWRITER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TSTREAMFILEWRITER )}, NULL },
{ "TTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( TTOC )}, NULL },
{ "TTOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( TTOD )}, NULL },
{ "TTOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( TTOS )}, NULL },
{ "TXMLDOCUMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TXMLDOCUMENT )}, NULL },
{ "TXMLITERATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( TXMLITERATOR )}, NULL },
{ "TXMLITERATORREGEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( TXMLITERATORREGEX )}, NULL },
{ "TXMLITERATORSCAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( TXMLITERATORSCAN )}, NULL },
{ "TXMLNODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( TXMLNODE )}, NULL },
{ "VALTOARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOARRAY )}, NULL },
{ "VALTOBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOBLOCK )}, NULL },
{ "VALTOCHARACTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOCHARACTER )}, NULL },
{ "VALTODATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTODATE )}, NULL },
{ "VALTOHASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOHASH )}, NULL },
{ "VALTOLOGICAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOLOGICAL )}, NULL },
{ "VALTONUMBER", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTONUMBER )}, NULL },
{ "VALTOOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOOBJECT )}, NULL },
{ "VALTOPRG", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOPRG )}, NULL },
{ "VALTOPRGEXP", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOPRGEXP )}, NULL },
{ "VALTOTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALTOTYPE )}, NULL },
{ "WAITFORTHREADS", {HB_FS_PUBLIC}, {HB_FUNCNAME( WAITFORTHREADS )}, NULL },
{ "WIDETOANSI", {HB_FS_PUBLIC}, {HB_FUNCNAME( WIDETOANSI )}, NULL },
{ "WILDMATCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( WILDMATCH )}, NULL },
{ "WIN32BMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( WIN32BMP )}, NULL },
{ "WIN32PRN", {HB_FS_PUBLIC}, {HB_FUNCNAME( WIN32PRN )}, NULL },
{ "XHBEDITOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHBEDITOR )}, NULL },
{ "XHB_ADEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_ADEL )}, NULL },
{ "XHB_AINS", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_AINS )}, NULL },
{ "XHB_ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_ALLTRIM )}, NULL },
{ "XHB_BITAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_BITAND )}, NULL },
{ "XHB_BITOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_BITOR )}, NULL },
{ "XHB_BITXOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_BITXOR )}, NULL },
{ "XHB_COPYFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_COPYFILE )}, NULL },
{ "XHB_DEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_DEC )}, NULL },
{ "XHB_DIV", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_DIV )}, NULL },
{ "XHB_EEQUAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_EEQUAL )}, NULL },
{ "XHB_EQUAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_EQUAL )}, NULL },
{ "XHB_ERRORLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_ERRORLOG )}, NULL },
{ "XHB_ERRORNEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_ERRORNEW )}, NULL },
{ "XHB_ERRORSYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_ERRORSYS )}, NULL },
{ "XHB_GREATER", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_GREATER )}, NULL },
{ "XHB_GREATEREQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_GREATEREQ )}, NULL },
{ "XHB_HASHERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_HASHERROR )}, NULL },
{ "XHB_INC", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_INC )}, NULL },
{ "XHB_INCLUDE", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_INCLUDE )}, NULL },
{ "XHB_INDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_INDEX )}, NULL },
{ "XHB_INKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_INKEY )}, NULL },
{ "XHB_KEYTRANS", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_KEYTRANS )}, NULL },
{ "XHB_LESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_LESS )}, NULL },
{ "XHB_LESSEQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_LESSEQ )}, NULL },
{ "XHB_LIB", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_LIB )}, NULL },
{ "XHB_MEMOEDIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_MEMOEDIT )}, NULL },
{ "XHB_MEMOWRIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_MEMOWRIT )}, NULL },
{ "XHB_MINUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_MINUS )}, NULL },
{ "XHB_MOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_MOD )}, NULL },
{ "XHB_MULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_MULT )}, NULL },
{ "XHB_NETNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_NETNAME )}, NULL },
{ "XHB_NOTEQUAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_NOTEQUAL )}, NULL },
{ "XHB_PLUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_PLUS )}, NULL },
{ "XHB_POW", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_POW )}, NULL },
{ "XHB_RESTSCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_RESTSCREEN )}, NULL },
{ "XHB_RTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_RTRIM )}, NULL },
{ "XHB_SAVESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_SAVESCREEN )}, NULL },
{ "XHB_SETTRACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_SETTRACE )}, NULL },
{ "XHB_SETTRACEFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_SETTRACEFILE )}, NULL },
{ "XHB_SETTRACESTACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_SETTRACESTACK )}, NULL },
{ "XHB_TMEMOEDITOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_TMEMOEDITOR )}, NULL },
{ "XHB_TRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB_TRIM )}, NULL },
{ "XHB__KEYBOARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( XHB__KEYBOARD )}, NULL },
{ "XISPRINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( XISPRINTER )}, NULL },
{ "_ARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( _ARRAY )}, NULL },
{ "_BLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( _BLOCK )}, NULL },
{ "_CHARACTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( _CHARACTER )}, NULL },
{ "_HASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( _HASH )}, NULL },
{ "_NUMERIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( _NUMERIC )}, NULL },
{ "__ACTIVESTRUCTURE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __ACTIVESTRUCTURE )}, NULL },
{ "__CSTR_COPYTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( __CSTR_COPYTO )}, NULL },
{ "__ERRORBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( __ERRORBLOCK )}, NULL },
{ "__INIT_LONGLONGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( __INIT_LONGLONGS )}, NULL },
{ "__MINIMALERRORHANDLER", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MINIMALERRORHANDLER )}, NULL },
{ "__MVSYMBOLINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVSYMBOLINFO )}, NULL },
{ "__OLEPDISP", {HB_FS_PUBLIC}, {HB_FUNCNAME( __OLEPDISP )}, NULL },
{ "__OUTDEBUG", {HB_FS_PUBLIC}, {HB_FUNCNAME( __OUTDEBUG )}, NULL },
{ "__SENDRAWMSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( __SENDRAWMSG )}, NULL },
{ "__HBEXTERN__XHB__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__XHB__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_XHB, "xhb\\xhb.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_XHB
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_XHB )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__XHB__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

