/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (32-bit)
 * Generated C source from "hbziparc\hbziparc.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_GETFILECOUNT );
HB_FUNC_EXTERN( HB_GETFILESINZIP );
HB_FUNC_EXTERN( HB_GETZIPCOMMENT );
HB_FUNC_EXTERN( HB_SETBUFFER );
HB_FUNC_EXTERN( HB_SETDISKZIP );
HB_FUNC_EXTERN( HB_SETZIPCOMMENT );
HB_FUNC_EXTERN( HB_UNZIPALLFILE );
HB_FUNC_EXTERN( HB_UNZIPFILE );
HB_FUNC_EXTERN( HB_UNZIPFILEINDEX );
HB_FUNC_EXTERN( HB_ZIPDELETEFILES );
HB_FUNC_EXTERN( HB_ZIPFILE );
HB_FUNC_EXTERN( HB_ZIPFILEBYPKSPAN );
HB_FUNC_EXTERN( HB_ZIPFILEBYTDSPAN );
HB_FUNC_EXTERN( HB_ZIPTESTPK );
HB_FUNC_EXTERN( HB_ZIPWITHPASSWORD );
HB_FUNC_EXTERN( SETZIPREADONLY );
HB_FUNC_EXTERN( TRANSFERFROMZIP );
HB_FUNC( __HBEXTERN__HBZIPARC__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBZIPARC )
{ "HB_GETFILECOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_GETFILECOUNT )}, NULL },
{ "HB_GETFILESINZIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_GETFILESINZIP )}, NULL },
{ "HB_GETZIPCOMMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_GETZIPCOMMENT )}, NULL },
{ "HB_SETBUFFER", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SETBUFFER )}, NULL },
{ "HB_SETDISKZIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SETDISKZIP )}, NULL },
{ "HB_SETZIPCOMMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SETZIPCOMMENT )}, NULL },
{ "HB_UNZIPALLFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPALLFILE )}, NULL },
{ "HB_UNZIPFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILE )}, NULL },
{ "HB_UNZIPFILEINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEINDEX )}, NULL },
{ "HB_ZIPDELETEFILES", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPDELETEFILES )}, NULL },
{ "HB_ZIPFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILE )}, NULL },
{ "HB_ZIPFILEBYPKSPAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILEBYPKSPAN )}, NULL },
{ "HB_ZIPFILEBYTDSPAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILEBYTDSPAN )}, NULL },
{ "HB_ZIPTESTPK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPTESTPK )}, NULL },
{ "HB_ZIPWITHPASSWORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPWITHPASSWORD )}, NULL },
{ "SETZIPREADONLY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETZIPREADONLY )}, NULL },
{ "TRANSFERFROMZIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFERFROMZIP )}, NULL },
{ "__HBEXTERN__HBZIPARC__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBZIPARC__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBZIPARC, "hbziparc\\hbziparc.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBZIPARC
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBZIPARC )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBZIPARC__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

