/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (64-bit)
 * Generated C source from "..\contrib\hbfship\hbfship.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( DBSETLOCATE );
HB_FUNC_EXTERN( DBSETLOCATEBLOCK );
HB_FUNC_EXTERN( EXECNAME );
HB_FUNC_EXTERN( EXECPIDNUM );
HB_FUNC_EXTERN( FIELDGETARR );
HB_FUNC_EXTERN( FIELDPUTARR );
HB_FUNC_EXTERN( INDEXCOUNT );
HB_FUNC_EXTERN( INDEXNAMES );
HB_FUNC_EXTERN( ISBEGSEQ );
HB_FUNC_EXTERN( ISDBEXCL );
HB_FUNC_EXTERN( ISDBFLOCK );
HB_FUNC_EXTERN( ISDBRLOCK );
HB_FUNC_EXTERN( ISFUNCTION );
HB_FUNC_EXTERN( SECONDSCPU );
HB_FUNC_EXTERN( STROCCURS );
HB_FUNC_EXTERN( STRPEEK );
HB_FUNC_EXTERN( STRPOKE );
HB_FUNC_EXTERN( USERSMAX );
HB_FUNC( __HBEXTERN__HBFSHIP__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBFSHIP )
{ "DBSETLOCATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSETLOCATE )}, NULL },
{ "DBSETLOCATEBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSETLOCATEBLOCK )}, NULL },
{ "EXECNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXECNAME )}, NULL },
{ "EXECPIDNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXECPIDNUM )}, NULL },
{ "FIELDGETARR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FIELDGETARR )}, NULL },
{ "FIELDPUTARR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FIELDPUTARR )}, NULL },
{ "INDEXCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( INDEXCOUNT )}, NULL },
{ "INDEXNAMES", {HB_FS_PUBLIC}, {HB_FUNCNAME( INDEXNAMES )}, NULL },
{ "ISBEGSEQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISBEGSEQ )}, NULL },
{ "ISDBEXCL", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISDBEXCL )}, NULL },
{ "ISDBFLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISDBFLOCK )}, NULL },
{ "ISDBRLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISDBRLOCK )}, NULL },
{ "ISFUNCTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISFUNCTION )}, NULL },
{ "SECONDSCPU", {HB_FS_PUBLIC}, {HB_FUNCNAME( SECONDSCPU )}, NULL },
{ "STROCCURS", {HB_FS_PUBLIC}, {HB_FUNCNAME( STROCCURS )}, NULL },
{ "STRPEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRPEEK )}, NULL },
{ "STRPOKE", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRPOKE )}, NULL },
{ "USERSMAX", {HB_FS_PUBLIC}, {HB_FUNCNAME( USERSMAX )}, NULL },
{ "__HBEXTERN__HBFSHIP__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBFSHIP__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBFSHIP, "..\\contrib\\hbfship\\hbfship.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBFSHIP
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBFSHIP )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBFSHIP__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

