/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (32-bit)
 * Generated C source from "hboslib\hboslib.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( OL_95APPTITLE );
HB_FUNC_EXTERN( OL_95VMTITLE );
HB_FUNC_EXTERN( OL_AUTOYIELD );
HB_FUNC_EXTERN( OL_ISMSWIN );
HB_FUNC_EXTERN( OL_ISNT );
HB_FUNC_EXTERN( OL_ISOS2 );
HB_FUNC_EXTERN( OL_ISOS2WIN );
HB_FUNC_EXTERN( OL_OSVERMAJ );
HB_FUNC_EXTERN( OL_OSVERMIN );
HB_FUNC_EXTERN( OL_WINCBCOPY );
HB_FUNC_EXTERN( OL_WINCBPASTE );
HB_FUNC_EXTERN( OL_WINFULLSCREEN );
HB_FUNC_EXTERN( OL_YIELD );
HB_FUNC( __HBEXTERN__HBOSLIB__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBOSLIB )
{ "OL_95APPTITLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_95APPTITLE )}, NULL },
{ "OL_95VMTITLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_95VMTITLE )}, NULL },
{ "OL_AUTOYIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_AUTOYIELD )}, NULL },
{ "OL_ISMSWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_ISMSWIN )}, NULL },
{ "OL_ISNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_ISNT )}, NULL },
{ "OL_ISOS2", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_ISOS2 )}, NULL },
{ "OL_ISOS2WIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_ISOS2WIN )}, NULL },
{ "OL_OSVERMAJ", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_OSVERMAJ )}, NULL },
{ "OL_OSVERMIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_OSVERMIN )}, NULL },
{ "OL_WINCBCOPY", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_WINCBCOPY )}, NULL },
{ "OL_WINCBPASTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_WINCBPASTE )}, NULL },
{ "OL_WINFULLSCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_WINFULLSCREEN )}, NULL },
{ "OL_YIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( OL_YIELD )}, NULL },
{ "__HBEXTERN__HBOSLIB__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBOSLIB__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBOSLIB, "hboslib\\hboslib.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBOSLIB
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBOSLIB )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBOSLIB__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

