/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (32-bit)
 * Generated C source from "..\contrib\hbssl\hbssl.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( BIO_CLEAR_FLAGS );
HB_FUNC_EXTERN( BIO_CTRL_PENDING );
HB_FUNC_EXTERN( BIO_CTRL_WPENDING );
HB_FUNC_EXTERN( BIO_DO_CONNECT );
HB_FUNC_EXTERN( BIO_EOF );
HB_FUNC_EXTERN( BIO_FLUSH );
HB_FUNC_EXTERN( BIO_FREE );
HB_FUNC_EXTERN( BIO_FREE_ALL );
HB_FUNC_EXTERN( BIO_GETS );
HB_FUNC_EXTERN( BIO_GET_CLOSE );
HB_FUNC_EXTERN( BIO_GET_CONN_HOSTNAME );
HB_FUNC_EXTERN( BIO_GET_CONN_INT_PORT );
HB_FUNC_EXTERN( BIO_GET_CONN_IP );
HB_FUNC_EXTERN( BIO_GET_CONN_PORT );
HB_FUNC_EXTERN( BIO_GET_FD );
HB_FUNC_EXTERN( BIO_GET_FLAGS );
HB_FUNC_EXTERN( BIO_GET_RETRY_REASON );
HB_FUNC_EXTERN( BIO_NEW );
HB_FUNC_EXTERN( BIO_NEW_ACCEPT );
HB_FUNC_EXTERN( BIO_NEW_CONNECT );
HB_FUNC_EXTERN( BIO_NEW_DGRAM );
HB_FUNC_EXTERN( BIO_NEW_FD );
HB_FUNC_EXTERN( BIO_NEW_FILE );
HB_FUNC_EXTERN( BIO_NEW_MEM_BUF );
HB_FUNC_EXTERN( BIO_NEW_SOCKET );
HB_FUNC_EXTERN( BIO_PUTS );
HB_FUNC_EXTERN( BIO_READ );
HB_FUNC_EXTERN( BIO_RESET );
HB_FUNC_EXTERN( BIO_RETRY_TYPE );
HB_FUNC_EXTERN( BIO_SEEK );
HB_FUNC_EXTERN( BIO_SET );
HB_FUNC_EXTERN( BIO_SET_CLOSE );
HB_FUNC_EXTERN( BIO_SET_CONN_HOSTNAME );
HB_FUNC_EXTERN( BIO_SET_CONN_INT_PORT );
HB_FUNC_EXTERN( BIO_SET_CONN_IP );
HB_FUNC_EXTERN( BIO_SET_CONN_PORT );
HB_FUNC_EXTERN( BIO_SET_FD );
HB_FUNC_EXTERN( BIO_SET_FLAGS );
HB_FUNC_EXTERN( BIO_SET_NBIO );
HB_FUNC_EXTERN( BIO_SET_RETRY_READ );
HB_FUNC_EXTERN( BIO_SET_RETRY_SPECIAL );
HB_FUNC_EXTERN( BIO_SET_RETRY_WRITE );
HB_FUNC_EXTERN( BIO_SHOULD_IO_SPECIAL );
HB_FUNC_EXTERN( BIO_SHOULD_READ );
HB_FUNC_EXTERN( BIO_SHOULD_RETRY );
HB_FUNC_EXTERN( BIO_SHOULD_WRITE );
HB_FUNC_EXTERN( BIO_TELL );
HB_FUNC_EXTERN( BIO_TEST_FLAGS );
HB_FUNC_EXTERN( BIO_VFREE );
HB_FUNC_EXTERN( BIO_WRITE );
HB_FUNC_EXTERN( ERR_ERROR_STRING );
HB_FUNC_EXTERN( ERR_FREE_STRINGS );
HB_FUNC_EXTERN( ERR_FUNC_ERROR_STRING );
HB_FUNC_EXTERN( ERR_GET_ERROR );
HB_FUNC_EXTERN( ERR_GET_ERROR_LINE );
HB_FUNC_EXTERN( ERR_GET_ERROR_LINE_DATA );
HB_FUNC_EXTERN( ERR_LIB_ERROR_STRING );
HB_FUNC_EXTERN( ERR_LOAD_BIO_STRINGS );
HB_FUNC_EXTERN( ERR_LOAD_CRYPTO_STRINGS );
HB_FUNC_EXTERN( ERR_LOAD_EVP_STRINGS );
HB_FUNC_EXTERN( ERR_LOAD_PEM_STRINGS );
HB_FUNC_EXTERN( ERR_PEEK_ERROR );
HB_FUNC_EXTERN( ERR_PEEK_ERROR_LINE );
HB_FUNC_EXTERN( ERR_PEEK_ERROR_LINE_DATA );
HB_FUNC_EXTERN( ERR_PEEK_LAST_ERROR );
HB_FUNC_EXTERN( ERR_PEEK_LAST_ERROR_LINE );
HB_FUNC_EXTERN( ERR_PEEK_LAST_ERROR_LINE_DATA );
HB_FUNC_EXTERN( ERR_PRINT_ERRORS );
HB_FUNC_EXTERN( ERR_REASON_ERROR_STRING );
HB_FUNC_EXTERN( EVP_BYTESTOKEY );
HB_FUNC_EXTERN( EVP_CIPHERFINAL );
HB_FUNC_EXTERN( EVP_CIPHERFINAL_EX );
HB_FUNC_EXTERN( EVP_CIPHERINIT );
HB_FUNC_EXTERN( EVP_CIPHERINIT_EX );
HB_FUNC_EXTERN( EVP_CIPHERUPDATE );
HB_FUNC_EXTERN( EVP_CIPHER_BLOCK_SIZE );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_CIPHER );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_CLEANUP );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_CTRL );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_INIT );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_KEY_LENGTH );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_NEW );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_RESET );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_SET_KEY_LENGTH );
HB_FUNC_EXTERN( EVP_CIPHER_CTX_SET_PADDING );
HB_FUNC_EXTERN( EVP_CIPHER_FLAGS );
HB_FUNC_EXTERN( EVP_CIPHER_IV_LENGTH );
HB_FUNC_EXTERN( EVP_CIPHER_KEY_LENGTH );
HB_FUNC_EXTERN( EVP_CIPHER_MODE );
HB_FUNC_EXTERN( EVP_CIPHER_NID );
HB_FUNC_EXTERN( EVP_CIPHER_TYPE );
HB_FUNC_EXTERN( EVP_CLEANUP );
HB_FUNC_EXTERN( EVP_DECODEFINAL );
HB_FUNC_EXTERN( EVP_DECODEINIT );
HB_FUNC_EXTERN( EVP_DECODEUPDATE );
HB_FUNC_EXTERN( EVP_DECRYPTFINAL );
HB_FUNC_EXTERN( EVP_DECRYPTFINAL_EX );
HB_FUNC_EXTERN( EVP_DECRYPTINIT );
HB_FUNC_EXTERN( EVP_DECRYPTINIT_EX );
HB_FUNC_EXTERN( EVP_DECRYPTUPDATE );
HB_FUNC_EXTERN( EVP_DIGESTFINAL );
HB_FUNC_EXTERN( EVP_DIGESTFINAL_EX );
HB_FUNC_EXTERN( EVP_DIGESTINIT );
HB_FUNC_EXTERN( EVP_DIGESTINIT_EX );
HB_FUNC_EXTERN( EVP_DIGESTUPDATE );
HB_FUNC_EXTERN( EVP_ENCODEFINAL );
HB_FUNC_EXTERN( EVP_ENCODEINIT );
HB_FUNC_EXTERN( EVP_ENCODEUPDATE );
HB_FUNC_EXTERN( EVP_ENCODE_CTX_NEW );
HB_FUNC_EXTERN( EVP_ENCRYPTFINAL );
HB_FUNC_EXTERN( EVP_ENCRYPTFINAL_EX );
HB_FUNC_EXTERN( EVP_ENCRYPTINIT );
HB_FUNC_EXTERN( EVP_ENCRYPTINIT_EX );
HB_FUNC_EXTERN( EVP_ENCRYPTUPDATE );
HB_FUNC_EXTERN( EVP_GET_CIPHERBYNAME );
HB_FUNC_EXTERN( EVP_GET_CIPHERBYNID );
HB_FUNC_EXTERN( EVP_GET_DIGESTBYNAME );
HB_FUNC_EXTERN( EVP_GET_DIGESTBYNID );
HB_FUNC_EXTERN( EVP_MD_BLOCK_SIZE );
HB_FUNC_EXTERN( EVP_MD_CTX_CLEANUP );
HB_FUNC_EXTERN( EVP_MD_CTX_COPY );
HB_FUNC_EXTERN( EVP_MD_CTX_COPY_EX );
HB_FUNC_EXTERN( EVP_MD_CTX_CREATE );
HB_FUNC_EXTERN( EVP_MD_CTX_INIT );
HB_FUNC_EXTERN( EVP_MD_CTX_MD );
HB_FUNC_EXTERN( EVP_MD_CTX_NEW );
HB_FUNC_EXTERN( EVP_MD_CTX_RESET );
HB_FUNC_EXTERN( EVP_MD_NID );
HB_FUNC_EXTERN( EVP_MD_PKEY_TYPE );
HB_FUNC_EXTERN( EVP_MD_SIZE );
HB_FUNC_EXTERN( EVP_MD_TYPE );
HB_FUNC_EXTERN( EVP_OPENFINAL );
HB_FUNC_EXTERN( EVP_OPENINIT );
HB_FUNC_EXTERN( EVP_OPENUPDATE );
HB_FUNC_EXTERN( EVP_PKEY_ASSIGN );
HB_FUNC_EXTERN( EVP_PKEY_ASSIGN_DH );
HB_FUNC_EXTERN( EVP_PKEY_ASSIGN_DSA );
HB_FUNC_EXTERN( EVP_PKEY_ASSIGN_RSA );
HB_FUNC_EXTERN( EVP_PKEY_BITS );
HB_FUNC_EXTERN( EVP_PKEY_FREE );
HB_FUNC_EXTERN( EVP_PKEY_NEW );
HB_FUNC_EXTERN( EVP_PKEY_SIZE );
HB_FUNC_EXTERN( EVP_PKEY_TYPE );
HB_FUNC_EXTERN( EVP_SEALFINAL );
HB_FUNC_EXTERN( EVP_SEALINIT );
HB_FUNC_EXTERN( EVP_SEALUPDATE );
HB_FUNC_EXTERN( EVP_SIGNFINAL );
HB_FUNC_EXTERN( EVP_SIGNINIT );
HB_FUNC_EXTERN( EVP_SIGNINIT_EX );
HB_FUNC_EXTERN( EVP_SIGNUPDATE );
HB_FUNC_EXTERN( EVP_VERIFYFINAL );
HB_FUNC_EXTERN( EVP_VERIFYINIT );
HB_FUNC_EXTERN( EVP_VERIFYINIT_EX );
HB_FUNC_EXTERN( EVP_VERIFYUPDATE );
HB_FUNC_EXTERN( HB_EVP_CIPHER_CTX_CREATE );
HB_FUNC_EXTERN( HB_EVP_ENCODE_CTX_CREATE );
HB_FUNC_EXTERN( HB_INETSSL_ACCEPT );
HB_FUNC_EXTERN( HB_INETSSL_CONNECT );
HB_FUNC_EXTERN( HB_SOCKETNEWSSL_ACCEPT );
HB_FUNC_EXTERN( HB_SOCKETNEWSSL_CONNECT );
HB_FUNC_EXTERN( HB_SSL_APPLINK );
HB_FUNC_EXTERN( HB_SSL_CONNECT_INET );
HB_FUNC_EXTERN( HB_SSL_CONNECT_SOCKET );
HB_FUNC_EXTERN( HB_SSL_NEW );
HB_FUNC_EXTERN( HB_SSL_READ_ALL );
HB_FUNC_EXTERN( HB_SSL_READ_LINE );
HB_FUNC_EXTERN( HB_SSL_STATIC );
HB_FUNC_EXTERN( OPENSSL_ADD_ALL_ALGORITHMS );
HB_FUNC_EXTERN( OPENSSL_ADD_ALL_CIPHERS );
HB_FUNC_EXTERN( OPENSSL_ADD_ALL_DIGESTS );
HB_FUNC_EXTERN( OPENSSL_VERSION );
HB_FUNC_EXTERN( OPENSSL_VERSION_NUM );
HB_FUNC_EXTERN( OPENSSL_VERSION_NUMBER );
HB_FUNC_EXTERN( PEM_READ_BIO_DHPARAMS );
HB_FUNC_EXTERN( PEM_READ_BIO_DSAPARAMS );
HB_FUNC_EXTERN( PEM_READ_BIO_DSAPRIVATEKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_DSA_PUBKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_PKCS7 );
HB_FUNC_EXTERN( PEM_READ_BIO_PRIVATEKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_PUBKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_RSAPRIVATEKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_RSAPUBLICKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_RSA_PUBKEY );
HB_FUNC_EXTERN( PEM_READ_BIO_X509 );
HB_FUNC_EXTERN( PEM_READ_BIO_X509_AUX );
HB_FUNC_EXTERN( PEM_READ_BIO_X509_CRL );
HB_FUNC_EXTERN( PEM_READ_BIO_X509_REQ );
HB_FUNC_EXTERN( PEM_READ_PRIVATEKEY );
HB_FUNC_EXTERN( PEM_READ_PUBKEY );
HB_FUNC_EXTERN( PEM_READ_X509 );
HB_FUNC_EXTERN( PEM_READ_X509_AUX );
HB_FUNC_EXTERN( RAND_ADD );
HB_FUNC_EXTERN( RAND_EVENT );
HB_FUNC_EXTERN( RAND_POLL );
HB_FUNC_EXTERN( RAND_SCREEN );
HB_FUNC_EXTERN( RAND_SEED );
HB_FUNC_EXTERN( RAND_STATUS );
HB_FUNC_EXTERN( SSLEAY );
HB_FUNC_EXTERN( SSLEAY_VERSION );
HB_FUNC_EXTERN( SSL_ACCEPT );
HB_FUNC_EXTERN( SSL_ADD_CLIENT_CA );
HB_FUNC_EXTERN( SSL_ALERT_DESC_STRING );
HB_FUNC_EXTERN( SSL_ALERT_DESC_STRING_LONG );
HB_FUNC_EXTERN( SSL_ALERT_TYPE_STRING );
HB_FUNC_EXTERN( SSL_ALERT_TYPE_STRING_LONG );
HB_FUNC_EXTERN( SSL_CHECK_PRIVATE_KEY );
HB_FUNC_EXTERN( SSL_CIPHER_DESCRIPTION );
HB_FUNC_EXTERN( SSL_CIPHER_GET_BITS );
HB_FUNC_EXTERN( SSL_CIPHER_GET_NAME );
HB_FUNC_EXTERN( SSL_CIPHER_GET_VERSION );
HB_FUNC_EXTERN( SSL_CLEAR );
HB_FUNC_EXTERN( SSL_CLEAR_NUM_RENEGOTIATIONS );
HB_FUNC_EXTERN( SSL_CONNECT );
HB_FUNC_EXTERN( SSL_COPY_SESSION_ID );
HB_FUNC_EXTERN( SSL_CTX_ADD_CLIENT_CA );
HB_FUNC_EXTERN( SSL_CTX_ADD_EXTRA_CHAIN_CERT );
HB_FUNC_EXTERN( SSL_CTX_ADD_SESSION );
HB_FUNC_EXTERN( SSL_CTX_CHECK_PRIVATE_KEY );
HB_FUNC_EXTERN( SSL_CTX_FLUSH_SESSIONS );
HB_FUNC_EXTERN( SSL_CTX_GET_CLIENT_CA_LIST );
HB_FUNC_EXTERN( SSL_CTX_GET_MODE );
HB_FUNC_EXTERN( SSL_CTX_GET_OPTIONS );
HB_FUNC_EXTERN( SSL_CTX_GET_QUIET_SHUTDOWN );
HB_FUNC_EXTERN( SSL_CTX_GET_SESSION_CACHE_MODE );
HB_FUNC_EXTERN( SSL_CTX_GET_TIMEOUT );
HB_FUNC_EXTERN( SSL_CTX_GET_VERIFY_MODE );
HB_FUNC_EXTERN( SSL_CTX_LOAD_VERIFY_LOCATIONS );
HB_FUNC_EXTERN( SSL_CTX_NEED_TMP_RSA );
HB_FUNC_EXTERN( SSL_CTX_NEW );
HB_FUNC_EXTERN( SSL_CTX_REMOVE_SESSION );
HB_FUNC_EXTERN( SSL_CTX_SESS_ACCEPT );
HB_FUNC_EXTERN( SSL_CTX_SESS_ACCEPT_GOOD );
HB_FUNC_EXTERN( SSL_CTX_SESS_ACCEPT_RENEGOTIATE );
HB_FUNC_EXTERN( SSL_CTX_SESS_CACHE_FULL );
HB_FUNC_EXTERN( SSL_CTX_SESS_CB_HITS );
HB_FUNC_EXTERN( SSL_CTX_SESS_CONNECT );
HB_FUNC_EXTERN( SSL_CTX_SESS_CONNECT_GOOD );
HB_FUNC_EXTERN( SSL_CTX_SESS_CONNECT_RENEGOTIATE );
HB_FUNC_EXTERN( SSL_CTX_SESS_GET_CACHE_SIZE );
HB_FUNC_EXTERN( SSL_CTX_SESS_HITS );
HB_FUNC_EXTERN( SSL_CTX_SESS_MISSES );
HB_FUNC_EXTERN( SSL_CTX_SESS_NUMBER );
HB_FUNC_EXTERN( SSL_CTX_SESS_SET_CACHE_SIZE );
HB_FUNC_EXTERN( SSL_CTX_SESS_TIMEOUTS );
HB_FUNC_EXTERN( SSL_CTX_SET_CIPHER_LIST );
HB_FUNC_EXTERN( SSL_CTX_SET_DEFAULT_READ_AHEAD );
HB_FUNC_EXTERN( SSL_CTX_SET_DEFAULT_VERIFY_PATHS );
HB_FUNC_EXTERN( SSL_CTX_SET_MODE );
HB_FUNC_EXTERN( SSL_CTX_SET_OPTIONS );
HB_FUNC_EXTERN( SSL_CTX_SET_QUIET_SHUTDOWN );
HB_FUNC_EXTERN( SSL_CTX_SET_SESSION_CACHE_MODE );
HB_FUNC_EXTERN( SSL_CTX_SET_SSL_VERSION );
HB_FUNC_EXTERN( SSL_CTX_SET_TIMEOUT );
HB_FUNC_EXTERN( SSL_CTX_USE_CERTIFICATE );
HB_FUNC_EXTERN( SSL_CTX_USE_CERTIFICATE_ASN1 );
HB_FUNC_EXTERN( SSL_CTX_USE_CERTIFICATE_CHAIN_FILE );
HB_FUNC_EXTERN( SSL_CTX_USE_CERTIFICATE_FILE );
HB_FUNC_EXTERN( SSL_CTX_USE_PRIVATEKEY );
HB_FUNC_EXTERN( SSL_CTX_USE_PRIVATEKEY_ASN1 );
HB_FUNC_EXTERN( SSL_CTX_USE_PRIVATEKEY_FILE );
HB_FUNC_EXTERN( SSL_CTX_USE_RSAPRIVATEKEY_ASN1 );
HB_FUNC_EXTERN( SSL_CTX_USE_RSAPRIVATEKEY_FILE );
HB_FUNC_EXTERN( SSL_DO_HANDSHAKE );
HB_FUNC_EXTERN( SSL_DUP );
HB_FUNC_EXTERN( SSL_GET_CERTIFICATE );
HB_FUNC_EXTERN( SSL_GET_CIPHER );
HB_FUNC_EXTERN( SSL_GET_CIPHERS );
HB_FUNC_EXTERN( SSL_GET_CIPHER_BITS );
HB_FUNC_EXTERN( SSL_GET_CIPHER_LIST );
HB_FUNC_EXTERN( SSL_GET_CIPHER_NAME );
HB_FUNC_EXTERN( SSL_GET_CIPHER_VERSION );
HB_FUNC_EXTERN( SSL_GET_CLIENT_CA_LIST );
HB_FUNC_EXTERN( SSL_GET_CURRENT_CIPHER );
HB_FUNC_EXTERN( SSL_GET_DEFAULT_TIMEOUT );
HB_FUNC_EXTERN( SSL_GET_ERROR );
HB_FUNC_EXTERN( SSL_GET_FD );
HB_FUNC_EXTERN( SSL_GET_MODE );
HB_FUNC_EXTERN( SSL_GET_OPTIONS );
HB_FUNC_EXTERN( SSL_GET_PEER_CERTIFICATE );
HB_FUNC_EXTERN( SSL_GET_QUIET_SHUTDOWN );
HB_FUNC_EXTERN( SSL_GET_RBIO );
HB_FUNC_EXTERN( SSL_GET_READ_AHEAD );
HB_FUNC_EXTERN( SSL_GET_RFD );
HB_FUNC_EXTERN( SSL_GET_SHARED_CIPHERS );
HB_FUNC_EXTERN( SSL_GET_SHUTDOWN );
HB_FUNC_EXTERN( SSL_GET_SSL_METHOD );
HB_FUNC_EXTERN( SSL_GET_STATE );
HB_FUNC_EXTERN( SSL_GET_VERIFY_MODE );
HB_FUNC_EXTERN( SSL_GET_VERIFY_RESULT );
HB_FUNC_EXTERN( SSL_GET_VERSION );
HB_FUNC_EXTERN( SSL_GET_WBIO );
HB_FUNC_EXTERN( SSL_GET_WFD );
HB_FUNC_EXTERN( SSL_INIT );
HB_FUNC_EXTERN( SSL_IN_ACCEPT_INIT );
HB_FUNC_EXTERN( SSL_IN_BEFORE );
HB_FUNC_EXTERN( SSL_IN_CONNECT_INIT );
HB_FUNC_EXTERN( SSL_IN_INIT );
HB_FUNC_EXTERN( SSL_IS_INIT_FINISHED );
HB_FUNC_EXTERN( SSL_LOAD_CLIENT_CA_FILE );
HB_FUNC_EXTERN( SSL_NEW );
HB_FUNC_EXTERN( SSL_NUM_RENEGOTIATIONS );
HB_FUNC_EXTERN( SSL_PEEK );
HB_FUNC_EXTERN( SSL_PENDING );
HB_FUNC_EXTERN( SSL_READ );
HB_FUNC_EXTERN( SSL_RENEGOTIATE );
HB_FUNC_EXTERN( SSL_RSTATE_STRING );
HB_FUNC_EXTERN( SSL_RSTATE_STRING_LONG );
HB_FUNC_EXTERN( SSL_SESSION_CMP );
HB_FUNC_EXTERN( SSL_SESSION_GET_TIME );
HB_FUNC_EXTERN( SSL_SESSION_GET_TIMEOUT );
HB_FUNC_EXTERN( SSL_SESSION_HASH );
HB_FUNC_EXTERN( SSL_SESSION_NEW );
HB_FUNC_EXTERN( SSL_SESSION_REUSED );
HB_FUNC_EXTERN( SSL_SESSION_SET_TIME );
HB_FUNC_EXTERN( SSL_SESSION_SET_TIMEOUT );
HB_FUNC_EXTERN( SSL_SET_ACCEPT_STATE );
HB_FUNC_EXTERN( SSL_SET_BIO );
HB_FUNC_EXTERN( SSL_SET_CIPHER_LIST );
HB_FUNC_EXTERN( SSL_SET_CONNECT_STATE );
HB_FUNC_EXTERN( SSL_SET_FD );
HB_FUNC_EXTERN( SSL_SET_MODE );
HB_FUNC_EXTERN( SSL_SET_MSG_CALLBACK );
HB_FUNC_EXTERN( SSL_SET_MTU );
HB_FUNC_EXTERN( SSL_SET_OPTIONS );
HB_FUNC_EXTERN( SSL_SET_QUIET_SHUTDOWN );
HB_FUNC_EXTERN( SSL_SET_READ_AHEAD );
HB_FUNC_EXTERN( SSL_SET_RFD );
HB_FUNC_EXTERN( SSL_SET_SHUTDOWN );
HB_FUNC_EXTERN( SSL_SET_SSL_METHOD );
HB_FUNC_EXTERN( SSL_SET_TLSEXT_HOST_NAME );
HB_FUNC_EXTERN( SSL_SET_VERIFY );
HB_FUNC_EXTERN( SSL_SET_VERIFY_RESULT );
HB_FUNC_EXTERN( SSL_SET_WFD );
HB_FUNC_EXTERN( SSL_SHUTDOWN );
HB_FUNC_EXTERN( SSL_STATE );
HB_FUNC_EXTERN( SSL_STATE_STRING );
HB_FUNC_EXTERN( SSL_STATE_STRING_LONG );
HB_FUNC_EXTERN( SSL_TOTAL_RENEGOTIATIONS );
HB_FUNC_EXTERN( SSL_USE_CERTIFICATE );
HB_FUNC_EXTERN( SSL_USE_CERTIFICATE_ASN1 );
HB_FUNC_EXTERN( SSL_USE_CERTIFICATE_FILE );
HB_FUNC_EXTERN( SSL_USE_PRIVATEKEY );
HB_FUNC_EXTERN( SSL_USE_PRIVATEKEY_ASN1 );
HB_FUNC_EXTERN( SSL_USE_PRIVATEKEY_FILE );
HB_FUNC_EXTERN( SSL_USE_RSAPRIVATEKEY_ASN1 );
HB_FUNC_EXTERN( SSL_USE_RSAPRIVATEKEY_FILE );
HB_FUNC_EXTERN( SSL_VERSION );
HB_FUNC_EXTERN( SSL_WANT );
HB_FUNC_EXTERN( SSL_WANT_NOTHING );
HB_FUNC_EXTERN( SSL_WANT_READ );
HB_FUNC_EXTERN( SSL_WANT_WRITE );
HB_FUNC_EXTERN( SSL_WANT_X509_LOOKUP );
HB_FUNC_EXTERN( SSL_WRITE );
HB_FUNC_EXTERN( X509_GET_ISSUER_NAME );
HB_FUNC_EXTERN( X509_GET_PUBKEY );
HB_FUNC_EXTERN( X509_GET_SUBJECT_NAME );
HB_FUNC_EXTERN( X509_NAME_ONELINE );
HB_FUNC( __HBEXTERN__HBSSL__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBSSL )
{ "BIO_CLEAR_FLAGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_CLEAR_FLAGS )}, NULL },
{ "BIO_CTRL_PENDING", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_CTRL_PENDING )}, NULL },
{ "BIO_CTRL_WPENDING", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_CTRL_WPENDING )}, NULL },
{ "BIO_DO_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_DO_CONNECT )}, NULL },
{ "BIO_EOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_EOF )}, NULL },
{ "BIO_FLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_FLUSH )}, NULL },
{ "BIO_FREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_FREE )}, NULL },
{ "BIO_FREE_ALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_FREE_ALL )}, NULL },
{ "BIO_GETS", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GETS )}, NULL },
{ "BIO_GET_CLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_CLOSE )}, NULL },
{ "BIO_GET_CONN_HOSTNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_CONN_HOSTNAME )}, NULL },
{ "BIO_GET_CONN_INT_PORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_CONN_INT_PORT )}, NULL },
{ "BIO_GET_CONN_IP", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_CONN_IP )}, NULL },
{ "BIO_GET_CONN_PORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_CONN_PORT )}, NULL },
{ "BIO_GET_FD", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_FD )}, NULL },
{ "BIO_GET_FLAGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_FLAGS )}, NULL },
{ "BIO_GET_RETRY_REASON", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_GET_RETRY_REASON )}, NULL },
{ "BIO_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW )}, NULL },
{ "BIO_NEW_ACCEPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_ACCEPT )}, NULL },
{ "BIO_NEW_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_CONNECT )}, NULL },
{ "BIO_NEW_DGRAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_DGRAM )}, NULL },
{ "BIO_NEW_FD", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_FD )}, NULL },
{ "BIO_NEW_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_FILE )}, NULL },
{ "BIO_NEW_MEM_BUF", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_MEM_BUF )}, NULL },
{ "BIO_NEW_SOCKET", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_NEW_SOCKET )}, NULL },
{ "BIO_PUTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_PUTS )}, NULL },
{ "BIO_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_READ )}, NULL },
{ "BIO_RESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_RESET )}, NULL },
{ "BIO_RETRY_TYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_RETRY_TYPE )}, NULL },
{ "BIO_SEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SEEK )}, NULL },
{ "BIO_SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET )}, NULL },
{ "BIO_SET_CLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_CLOSE )}, NULL },
{ "BIO_SET_CONN_HOSTNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_CONN_HOSTNAME )}, NULL },
{ "BIO_SET_CONN_INT_PORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_CONN_INT_PORT )}, NULL },
{ "BIO_SET_CONN_IP", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_CONN_IP )}, NULL },
{ "BIO_SET_CONN_PORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_CONN_PORT )}, NULL },
{ "BIO_SET_FD", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_FD )}, NULL },
{ "BIO_SET_FLAGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_FLAGS )}, NULL },
{ "BIO_SET_NBIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_NBIO )}, NULL },
{ "BIO_SET_RETRY_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_RETRY_READ )}, NULL },
{ "BIO_SET_RETRY_SPECIAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_RETRY_SPECIAL )}, NULL },
{ "BIO_SET_RETRY_WRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SET_RETRY_WRITE )}, NULL },
{ "BIO_SHOULD_IO_SPECIAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SHOULD_IO_SPECIAL )}, NULL },
{ "BIO_SHOULD_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SHOULD_READ )}, NULL },
{ "BIO_SHOULD_RETRY", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SHOULD_RETRY )}, NULL },
{ "BIO_SHOULD_WRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_SHOULD_WRITE )}, NULL },
{ "BIO_TELL", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_TELL )}, NULL },
{ "BIO_TEST_FLAGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_TEST_FLAGS )}, NULL },
{ "BIO_VFREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_VFREE )}, NULL },
{ "BIO_WRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIO_WRITE )}, NULL },
{ "ERR_ERROR_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_ERROR_STRING )}, NULL },
{ "ERR_FREE_STRINGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_FREE_STRINGS )}, NULL },
{ "ERR_FUNC_ERROR_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_FUNC_ERROR_STRING )}, NULL },
{ "ERR_GET_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_GET_ERROR )}, NULL },
{ "ERR_GET_ERROR_LINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_GET_ERROR_LINE )}, NULL },
{ "ERR_GET_ERROR_LINE_DATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_GET_ERROR_LINE_DATA )}, NULL },
{ "ERR_LIB_ERROR_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_LIB_ERROR_STRING )}, NULL },
{ "ERR_LOAD_BIO_STRINGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_LOAD_BIO_STRINGS )}, NULL },
{ "ERR_LOAD_CRYPTO_STRINGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_LOAD_CRYPTO_STRINGS )}, NULL },
{ "ERR_LOAD_EVP_STRINGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_LOAD_EVP_STRINGS )}, NULL },
{ "ERR_LOAD_PEM_STRINGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_LOAD_PEM_STRINGS )}, NULL },
{ "ERR_PEEK_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PEEK_ERROR )}, NULL },
{ "ERR_PEEK_ERROR_LINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PEEK_ERROR_LINE )}, NULL },
{ "ERR_PEEK_ERROR_LINE_DATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PEEK_ERROR_LINE_DATA )}, NULL },
{ "ERR_PEEK_LAST_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PEEK_LAST_ERROR )}, NULL },
{ "ERR_PEEK_LAST_ERROR_LINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PEEK_LAST_ERROR_LINE )}, NULL },
{ "ERR_PEEK_LAST_ERROR_LINE_DATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PEEK_LAST_ERROR_LINE_DATA )}, NULL },
{ "ERR_PRINT_ERRORS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_PRINT_ERRORS )}, NULL },
{ "ERR_REASON_ERROR_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERR_REASON_ERROR_STRING )}, NULL },
{ "EVP_BYTESTOKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_BYTESTOKEY )}, NULL },
{ "EVP_CIPHERFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHERFINAL )}, NULL },
{ "EVP_CIPHERFINAL_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHERFINAL_EX )}, NULL },
{ "EVP_CIPHERINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHERINIT )}, NULL },
{ "EVP_CIPHERINIT_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHERINIT_EX )}, NULL },
{ "EVP_CIPHERUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHERUPDATE )}, NULL },
{ "EVP_CIPHER_BLOCK_SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_BLOCK_SIZE )}, NULL },
{ "EVP_CIPHER_CTX_CIPHER", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_CIPHER )}, NULL },
{ "EVP_CIPHER_CTX_CLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_CLEANUP )}, NULL },
{ "EVP_CIPHER_CTX_CTRL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_CTRL )}, NULL },
{ "EVP_CIPHER_CTX_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_INIT )}, NULL },
{ "EVP_CIPHER_CTX_KEY_LENGTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_KEY_LENGTH )}, NULL },
{ "EVP_CIPHER_CTX_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_NEW )}, NULL },
{ "EVP_CIPHER_CTX_RESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_RESET )}, NULL },
{ "EVP_CIPHER_CTX_SET_KEY_LENGTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_SET_KEY_LENGTH )}, NULL },
{ "EVP_CIPHER_CTX_SET_PADDING", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_CTX_SET_PADDING )}, NULL },
{ "EVP_CIPHER_FLAGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_FLAGS )}, NULL },
{ "EVP_CIPHER_IV_LENGTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_IV_LENGTH )}, NULL },
{ "EVP_CIPHER_KEY_LENGTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_KEY_LENGTH )}, NULL },
{ "EVP_CIPHER_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_MODE )}, NULL },
{ "EVP_CIPHER_NID", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_NID )}, NULL },
{ "EVP_CIPHER_TYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CIPHER_TYPE )}, NULL },
{ "EVP_CLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_CLEANUP )}, NULL },
{ "EVP_DECODEFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECODEFINAL )}, NULL },
{ "EVP_DECODEINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECODEINIT )}, NULL },
{ "EVP_DECODEUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECODEUPDATE )}, NULL },
{ "EVP_DECRYPTFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECRYPTFINAL )}, NULL },
{ "EVP_DECRYPTFINAL_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECRYPTFINAL_EX )}, NULL },
{ "EVP_DECRYPTINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECRYPTINIT )}, NULL },
{ "EVP_DECRYPTINIT_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECRYPTINIT_EX )}, NULL },
{ "EVP_DECRYPTUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DECRYPTUPDATE )}, NULL },
{ "EVP_DIGESTFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DIGESTFINAL )}, NULL },
{ "EVP_DIGESTFINAL_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DIGESTFINAL_EX )}, NULL },
{ "EVP_DIGESTINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DIGESTINIT )}, NULL },
{ "EVP_DIGESTINIT_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DIGESTINIT_EX )}, NULL },
{ "EVP_DIGESTUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_DIGESTUPDATE )}, NULL },
{ "EVP_ENCODEFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCODEFINAL )}, NULL },
{ "EVP_ENCODEINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCODEINIT )}, NULL },
{ "EVP_ENCODEUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCODEUPDATE )}, NULL },
{ "EVP_ENCODE_CTX_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCODE_CTX_NEW )}, NULL },
{ "EVP_ENCRYPTFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCRYPTFINAL )}, NULL },
{ "EVP_ENCRYPTFINAL_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCRYPTFINAL_EX )}, NULL },
{ "EVP_ENCRYPTINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCRYPTINIT )}, NULL },
{ "EVP_ENCRYPTINIT_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCRYPTINIT_EX )}, NULL },
{ "EVP_ENCRYPTUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_ENCRYPTUPDATE )}, NULL },
{ "EVP_GET_CIPHERBYNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_GET_CIPHERBYNAME )}, NULL },
{ "EVP_GET_CIPHERBYNID", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_GET_CIPHERBYNID )}, NULL },
{ "EVP_GET_DIGESTBYNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_GET_DIGESTBYNAME )}, NULL },
{ "EVP_GET_DIGESTBYNID", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_GET_DIGESTBYNID )}, NULL },
{ "EVP_MD_BLOCK_SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_BLOCK_SIZE )}, NULL },
{ "EVP_MD_CTX_CLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_CLEANUP )}, NULL },
{ "EVP_MD_CTX_COPY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_COPY )}, NULL },
{ "EVP_MD_CTX_COPY_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_COPY_EX )}, NULL },
{ "EVP_MD_CTX_CREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_CREATE )}, NULL },
{ "EVP_MD_CTX_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_INIT )}, NULL },
{ "EVP_MD_CTX_MD", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_MD )}, NULL },
{ "EVP_MD_CTX_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_NEW )}, NULL },
{ "EVP_MD_CTX_RESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_CTX_RESET )}, NULL },
{ "EVP_MD_NID", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_NID )}, NULL },
{ "EVP_MD_PKEY_TYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_PKEY_TYPE )}, NULL },
{ "EVP_MD_SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_SIZE )}, NULL },
{ "EVP_MD_TYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_MD_TYPE )}, NULL },
{ "EVP_OPENFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_OPENFINAL )}, NULL },
{ "EVP_OPENINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_OPENINIT )}, NULL },
{ "EVP_OPENUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_OPENUPDATE )}, NULL },
{ "EVP_PKEY_ASSIGN", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_ASSIGN )}, NULL },
{ "EVP_PKEY_ASSIGN_DH", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_ASSIGN_DH )}, NULL },
{ "EVP_PKEY_ASSIGN_DSA", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_ASSIGN_DSA )}, NULL },
{ "EVP_PKEY_ASSIGN_RSA", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_ASSIGN_RSA )}, NULL },
{ "EVP_PKEY_BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_BITS )}, NULL },
{ "EVP_PKEY_FREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_FREE )}, NULL },
{ "EVP_PKEY_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_NEW )}, NULL },
{ "EVP_PKEY_SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_SIZE )}, NULL },
{ "EVP_PKEY_TYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_PKEY_TYPE )}, NULL },
{ "EVP_SEALFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SEALFINAL )}, NULL },
{ "EVP_SEALINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SEALINIT )}, NULL },
{ "EVP_SEALUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SEALUPDATE )}, NULL },
{ "EVP_SIGNFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SIGNFINAL )}, NULL },
{ "EVP_SIGNINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SIGNINIT )}, NULL },
{ "EVP_SIGNINIT_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SIGNINIT_EX )}, NULL },
{ "EVP_SIGNUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_SIGNUPDATE )}, NULL },
{ "EVP_VERIFYFINAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_VERIFYFINAL )}, NULL },
{ "EVP_VERIFYINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_VERIFYINIT )}, NULL },
{ "EVP_VERIFYINIT_EX", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_VERIFYINIT_EX )}, NULL },
{ "EVP_VERIFYUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EVP_VERIFYUPDATE )}, NULL },
{ "HB_EVP_CIPHER_CTX_CREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_EVP_CIPHER_CTX_CREATE )}, NULL },
{ "HB_EVP_ENCODE_CTX_CREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_EVP_ENCODE_CTX_CREATE )}, NULL },
{ "HB_INETSSL_ACCEPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_INETSSL_ACCEPT )}, NULL },
{ "HB_INETSSL_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_INETSSL_CONNECT )}, NULL },
{ "HB_SOCKETNEWSSL_ACCEPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SOCKETNEWSSL_ACCEPT )}, NULL },
{ "HB_SOCKETNEWSSL_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SOCKETNEWSSL_CONNECT )}, NULL },
{ "HB_SSL_APPLINK", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_APPLINK )}, NULL },
{ "HB_SSL_CONNECT_INET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_CONNECT_INET )}, NULL },
{ "HB_SSL_CONNECT_SOCKET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_CONNECT_SOCKET )}, NULL },
{ "HB_SSL_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_NEW )}, NULL },
{ "HB_SSL_READ_ALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_READ_ALL )}, NULL },
{ "HB_SSL_READ_LINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_READ_LINE )}, NULL },
{ "HB_SSL_STATIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_SSL_STATIC )}, NULL },
{ "OPENSSL_ADD_ALL_ALGORITHMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPENSSL_ADD_ALL_ALGORITHMS )}, NULL },
{ "OPENSSL_ADD_ALL_CIPHERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPENSSL_ADD_ALL_CIPHERS )}, NULL },
{ "OPENSSL_ADD_ALL_DIGESTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPENSSL_ADD_ALL_DIGESTS )}, NULL },
{ "OPENSSL_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPENSSL_VERSION )}, NULL },
{ "OPENSSL_VERSION_NUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPENSSL_VERSION_NUM )}, NULL },
{ "OPENSSL_VERSION_NUMBER", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPENSSL_VERSION_NUMBER )}, NULL },
{ "PEM_READ_BIO_DHPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_DHPARAMS )}, NULL },
{ "PEM_READ_BIO_DSAPARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_DSAPARAMS )}, NULL },
{ "PEM_READ_BIO_DSAPRIVATEKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_DSAPRIVATEKEY )}, NULL },
{ "PEM_READ_BIO_DSA_PUBKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_DSA_PUBKEY )}, NULL },
{ "PEM_READ_BIO_PKCS7", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_PKCS7 )}, NULL },
{ "PEM_READ_BIO_PRIVATEKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_PRIVATEKEY )}, NULL },
{ "PEM_READ_BIO_PUBKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_PUBKEY )}, NULL },
{ "PEM_READ_BIO_RSAPRIVATEKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_RSAPRIVATEKEY )}, NULL },
{ "PEM_READ_BIO_RSAPUBLICKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_RSAPUBLICKEY )}, NULL },
{ "PEM_READ_BIO_RSA_PUBKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_RSA_PUBKEY )}, NULL },
{ "PEM_READ_BIO_X509", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_X509 )}, NULL },
{ "PEM_READ_BIO_X509_AUX", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_X509_AUX )}, NULL },
{ "PEM_READ_BIO_X509_CRL", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_X509_CRL )}, NULL },
{ "PEM_READ_BIO_X509_REQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_BIO_X509_REQ )}, NULL },
{ "PEM_READ_PRIVATEKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_PRIVATEKEY )}, NULL },
{ "PEM_READ_PUBKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_PUBKEY )}, NULL },
{ "PEM_READ_X509", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_X509 )}, NULL },
{ "PEM_READ_X509_AUX", {HB_FS_PUBLIC}, {HB_FUNCNAME( PEM_READ_X509_AUX )}, NULL },
{ "RAND_ADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND_ADD )}, NULL },
{ "RAND_EVENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND_EVENT )}, NULL },
{ "RAND_POLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND_POLL )}, NULL },
{ "RAND_SCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND_SCREEN )}, NULL },
{ "RAND_SEED", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND_SEED )}, NULL },
{ "RAND_STATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND_STATUS )}, NULL },
{ "SSLEAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSLEAY )}, NULL },
{ "SSLEAY_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSLEAY_VERSION )}, NULL },
{ "SSL_ACCEPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_ACCEPT )}, NULL },
{ "SSL_ADD_CLIENT_CA", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_ADD_CLIENT_CA )}, NULL },
{ "SSL_ALERT_DESC_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_ALERT_DESC_STRING )}, NULL },
{ "SSL_ALERT_DESC_STRING_LONG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_ALERT_DESC_STRING_LONG )}, NULL },
{ "SSL_ALERT_TYPE_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_ALERT_TYPE_STRING )}, NULL },
{ "SSL_ALERT_TYPE_STRING_LONG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_ALERT_TYPE_STRING_LONG )}, NULL },
{ "SSL_CHECK_PRIVATE_KEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CHECK_PRIVATE_KEY )}, NULL },
{ "SSL_CIPHER_DESCRIPTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CIPHER_DESCRIPTION )}, NULL },
{ "SSL_CIPHER_GET_BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CIPHER_GET_BITS )}, NULL },
{ "SSL_CIPHER_GET_NAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CIPHER_GET_NAME )}, NULL },
{ "SSL_CIPHER_GET_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CIPHER_GET_VERSION )}, NULL },
{ "SSL_CLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CLEAR )}, NULL },
{ "SSL_CLEAR_NUM_RENEGOTIATIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CLEAR_NUM_RENEGOTIATIONS )}, NULL },
{ "SSL_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CONNECT )}, NULL },
{ "SSL_COPY_SESSION_ID", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_COPY_SESSION_ID )}, NULL },
{ "SSL_CTX_ADD_CLIENT_CA", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_ADD_CLIENT_CA )}, NULL },
{ "SSL_CTX_ADD_EXTRA_CHAIN_CERT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_ADD_EXTRA_CHAIN_CERT )}, NULL },
{ "SSL_CTX_ADD_SESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_ADD_SESSION )}, NULL },
{ "SSL_CTX_CHECK_PRIVATE_KEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_CHECK_PRIVATE_KEY )}, NULL },
{ "SSL_CTX_FLUSH_SESSIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_FLUSH_SESSIONS )}, NULL },
{ "SSL_CTX_GET_CLIENT_CA_LIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_CLIENT_CA_LIST )}, NULL },
{ "SSL_CTX_GET_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_MODE )}, NULL },
{ "SSL_CTX_GET_OPTIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_OPTIONS )}, NULL },
{ "SSL_CTX_GET_QUIET_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_QUIET_SHUTDOWN )}, NULL },
{ "SSL_CTX_GET_SESSION_CACHE_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_SESSION_CACHE_MODE )}, NULL },
{ "SSL_CTX_GET_TIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_TIMEOUT )}, NULL },
{ "SSL_CTX_GET_VERIFY_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_GET_VERIFY_MODE )}, NULL },
{ "SSL_CTX_LOAD_VERIFY_LOCATIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_LOAD_VERIFY_LOCATIONS )}, NULL },
{ "SSL_CTX_NEED_TMP_RSA", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_NEED_TMP_RSA )}, NULL },
{ "SSL_CTX_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_NEW )}, NULL },
{ "SSL_CTX_REMOVE_SESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_REMOVE_SESSION )}, NULL },
{ "SSL_CTX_SESS_ACCEPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_ACCEPT )}, NULL },
{ "SSL_CTX_SESS_ACCEPT_GOOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_ACCEPT_GOOD )}, NULL },
{ "SSL_CTX_SESS_ACCEPT_RENEGOTIATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_ACCEPT_RENEGOTIATE )}, NULL },
{ "SSL_CTX_SESS_CACHE_FULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_CACHE_FULL )}, NULL },
{ "SSL_CTX_SESS_CB_HITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_CB_HITS )}, NULL },
{ "SSL_CTX_SESS_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_CONNECT )}, NULL },
{ "SSL_CTX_SESS_CONNECT_GOOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_CONNECT_GOOD )}, NULL },
{ "SSL_CTX_SESS_CONNECT_RENEGOTIATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_CONNECT_RENEGOTIATE )}, NULL },
{ "SSL_CTX_SESS_GET_CACHE_SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_GET_CACHE_SIZE )}, NULL },
{ "SSL_CTX_SESS_HITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_HITS )}, NULL },
{ "SSL_CTX_SESS_MISSES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_MISSES )}, NULL },
{ "SSL_CTX_SESS_NUMBER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_NUMBER )}, NULL },
{ "SSL_CTX_SESS_SET_CACHE_SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_SET_CACHE_SIZE )}, NULL },
{ "SSL_CTX_SESS_TIMEOUTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SESS_TIMEOUTS )}, NULL },
{ "SSL_CTX_SET_CIPHER_LIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_CIPHER_LIST )}, NULL },
{ "SSL_CTX_SET_DEFAULT_READ_AHEAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_DEFAULT_READ_AHEAD )}, NULL },
{ "SSL_CTX_SET_DEFAULT_VERIFY_PATHS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_DEFAULT_VERIFY_PATHS )}, NULL },
{ "SSL_CTX_SET_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_MODE )}, NULL },
{ "SSL_CTX_SET_OPTIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_OPTIONS )}, NULL },
{ "SSL_CTX_SET_QUIET_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_QUIET_SHUTDOWN )}, NULL },
{ "SSL_CTX_SET_SESSION_CACHE_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_SESSION_CACHE_MODE )}, NULL },
{ "SSL_CTX_SET_SSL_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_SSL_VERSION )}, NULL },
{ "SSL_CTX_SET_TIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_SET_TIMEOUT )}, NULL },
{ "SSL_CTX_USE_CERTIFICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_CERTIFICATE )}, NULL },
{ "SSL_CTX_USE_CERTIFICATE_ASN1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_CERTIFICATE_ASN1 )}, NULL },
{ "SSL_CTX_USE_CERTIFICATE_CHAIN_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_CERTIFICATE_CHAIN_FILE )}, NULL },
{ "SSL_CTX_USE_CERTIFICATE_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_CERTIFICATE_FILE )}, NULL },
{ "SSL_CTX_USE_PRIVATEKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_PRIVATEKEY )}, NULL },
{ "SSL_CTX_USE_PRIVATEKEY_ASN1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_PRIVATEKEY_ASN1 )}, NULL },
{ "SSL_CTX_USE_PRIVATEKEY_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_PRIVATEKEY_FILE )}, NULL },
{ "SSL_CTX_USE_RSAPRIVATEKEY_ASN1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_RSAPRIVATEKEY_ASN1 )}, NULL },
{ "SSL_CTX_USE_RSAPRIVATEKEY_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_CTX_USE_RSAPRIVATEKEY_FILE )}, NULL },
{ "SSL_DO_HANDSHAKE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_DO_HANDSHAKE )}, NULL },
{ "SSL_DUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_DUP )}, NULL },
{ "SSL_GET_CERTIFICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CERTIFICATE )}, NULL },
{ "SSL_GET_CIPHER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CIPHER )}, NULL },
{ "SSL_GET_CIPHERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CIPHERS )}, NULL },
{ "SSL_GET_CIPHER_BITS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CIPHER_BITS )}, NULL },
{ "SSL_GET_CIPHER_LIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CIPHER_LIST )}, NULL },
{ "SSL_GET_CIPHER_NAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CIPHER_NAME )}, NULL },
{ "SSL_GET_CIPHER_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CIPHER_VERSION )}, NULL },
{ "SSL_GET_CLIENT_CA_LIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CLIENT_CA_LIST )}, NULL },
{ "SSL_GET_CURRENT_CIPHER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_CURRENT_CIPHER )}, NULL },
{ "SSL_GET_DEFAULT_TIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_DEFAULT_TIMEOUT )}, NULL },
{ "SSL_GET_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_ERROR )}, NULL },
{ "SSL_GET_FD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_FD )}, NULL },
{ "SSL_GET_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_MODE )}, NULL },
{ "SSL_GET_OPTIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_OPTIONS )}, NULL },
{ "SSL_GET_PEER_CERTIFICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_PEER_CERTIFICATE )}, NULL },
{ "SSL_GET_QUIET_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_QUIET_SHUTDOWN )}, NULL },
{ "SSL_GET_RBIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_RBIO )}, NULL },
{ "SSL_GET_READ_AHEAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_READ_AHEAD )}, NULL },
{ "SSL_GET_RFD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_RFD )}, NULL },
{ "SSL_GET_SHARED_CIPHERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_SHARED_CIPHERS )}, NULL },
{ "SSL_GET_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_SHUTDOWN )}, NULL },
{ "SSL_GET_SSL_METHOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_SSL_METHOD )}, NULL },
{ "SSL_GET_STATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_STATE )}, NULL },
{ "SSL_GET_VERIFY_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_VERIFY_MODE )}, NULL },
{ "SSL_GET_VERIFY_RESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_VERIFY_RESULT )}, NULL },
{ "SSL_GET_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_VERSION )}, NULL },
{ "SSL_GET_WBIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_WBIO )}, NULL },
{ "SSL_GET_WFD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_GET_WFD )}, NULL },
{ "SSL_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_INIT )}, NULL },
{ "SSL_IN_ACCEPT_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_IN_ACCEPT_INIT )}, NULL },
{ "SSL_IN_BEFORE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_IN_BEFORE )}, NULL },
{ "SSL_IN_CONNECT_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_IN_CONNECT_INIT )}, NULL },
{ "SSL_IN_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_IN_INIT )}, NULL },
{ "SSL_IS_INIT_FINISHED", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_IS_INIT_FINISHED )}, NULL },
{ "SSL_LOAD_CLIENT_CA_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_LOAD_CLIENT_CA_FILE )}, NULL },
{ "SSL_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_NEW )}, NULL },
{ "SSL_NUM_RENEGOTIATIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_NUM_RENEGOTIATIONS )}, NULL },
{ "SSL_PEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_PEEK )}, NULL },
{ "SSL_PENDING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_PENDING )}, NULL },
{ "SSL_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_READ )}, NULL },
{ "SSL_RENEGOTIATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_RENEGOTIATE )}, NULL },
{ "SSL_RSTATE_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_RSTATE_STRING )}, NULL },
{ "SSL_RSTATE_STRING_LONG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_RSTATE_STRING_LONG )}, NULL },
{ "SSL_SESSION_CMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_CMP )}, NULL },
{ "SSL_SESSION_GET_TIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_GET_TIME )}, NULL },
{ "SSL_SESSION_GET_TIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_GET_TIMEOUT )}, NULL },
{ "SSL_SESSION_HASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_HASH )}, NULL },
{ "SSL_SESSION_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_NEW )}, NULL },
{ "SSL_SESSION_REUSED", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_REUSED )}, NULL },
{ "SSL_SESSION_SET_TIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_SET_TIME )}, NULL },
{ "SSL_SESSION_SET_TIMEOUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SESSION_SET_TIMEOUT )}, NULL },
{ "SSL_SET_ACCEPT_STATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_ACCEPT_STATE )}, NULL },
{ "SSL_SET_BIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_BIO )}, NULL },
{ "SSL_SET_CIPHER_LIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_CIPHER_LIST )}, NULL },
{ "SSL_SET_CONNECT_STATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_CONNECT_STATE )}, NULL },
{ "SSL_SET_FD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_FD )}, NULL },
{ "SSL_SET_MODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_MODE )}, NULL },
{ "SSL_SET_MSG_CALLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_MSG_CALLBACK )}, NULL },
{ "SSL_SET_MTU", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_MTU )}, NULL },
{ "SSL_SET_OPTIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_OPTIONS )}, NULL },
{ "SSL_SET_QUIET_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_QUIET_SHUTDOWN )}, NULL },
{ "SSL_SET_READ_AHEAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_READ_AHEAD )}, NULL },
{ "SSL_SET_RFD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_RFD )}, NULL },
{ "SSL_SET_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_SHUTDOWN )}, NULL },
{ "SSL_SET_SSL_METHOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_SSL_METHOD )}, NULL },
{ "SSL_SET_TLSEXT_HOST_NAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_TLSEXT_HOST_NAME )}, NULL },
{ "SSL_SET_VERIFY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_VERIFY )}, NULL },
{ "SSL_SET_VERIFY_RESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_VERIFY_RESULT )}, NULL },
{ "SSL_SET_WFD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SET_WFD )}, NULL },
{ "SSL_SHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_SHUTDOWN )}, NULL },
{ "SSL_STATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_STATE )}, NULL },
{ "SSL_STATE_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_STATE_STRING )}, NULL },
{ "SSL_STATE_STRING_LONG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_STATE_STRING_LONG )}, NULL },
{ "SSL_TOTAL_RENEGOTIATIONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_TOTAL_RENEGOTIATIONS )}, NULL },
{ "SSL_USE_CERTIFICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_CERTIFICATE )}, NULL },
{ "SSL_USE_CERTIFICATE_ASN1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_CERTIFICATE_ASN1 )}, NULL },
{ "SSL_USE_CERTIFICATE_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_CERTIFICATE_FILE )}, NULL },
{ "SSL_USE_PRIVATEKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_PRIVATEKEY )}, NULL },
{ "SSL_USE_PRIVATEKEY_ASN1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_PRIVATEKEY_ASN1 )}, NULL },
{ "SSL_USE_PRIVATEKEY_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_PRIVATEKEY_FILE )}, NULL },
{ "SSL_USE_RSAPRIVATEKEY_ASN1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_RSAPRIVATEKEY_ASN1 )}, NULL },
{ "SSL_USE_RSAPRIVATEKEY_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_USE_RSAPRIVATEKEY_FILE )}, NULL },
{ "SSL_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_VERSION )}, NULL },
{ "SSL_WANT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_WANT )}, NULL },
{ "SSL_WANT_NOTHING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_WANT_NOTHING )}, NULL },
{ "SSL_WANT_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_WANT_READ )}, NULL },
{ "SSL_WANT_WRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_WANT_WRITE )}, NULL },
{ "SSL_WANT_X509_LOOKUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_WANT_X509_LOOKUP )}, NULL },
{ "SSL_WRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SSL_WRITE )}, NULL },
{ "X509_GET_ISSUER_NAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( X509_GET_ISSUER_NAME )}, NULL },
{ "X509_GET_PUBKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( X509_GET_PUBKEY )}, NULL },
{ "X509_GET_SUBJECT_NAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( X509_GET_SUBJECT_NAME )}, NULL },
{ "X509_NAME_ONELINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( X509_NAME_ONELINE )}, NULL },
{ "__HBEXTERN__HBSSL__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBSSL__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBSSL, "..\\contrib\\hbssl\\hbssl.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBSSL
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBSSL )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBSSL__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

