/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (64-bit)
 * Generated C source from "hbzebra\hbzebra.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_ZEBRA_CREATE_CODABAR );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_CODE11 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_CODE128 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_CODE39 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_CODE93 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_DATAMATRIX );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_EAN13 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_EAN8 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_ITF );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_MSI );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_PDF417 );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_QRCODE );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_UPCA );
HB_FUNC_EXTERN( HB_ZEBRA_CREATE_UPCE );
HB_FUNC_EXTERN( HB_ZEBRA_DESTROY );
HB_FUNC_EXTERN( HB_ZEBRA_DRAW );
HB_FUNC_EXTERN( HB_ZEBRA_GETCODE );
HB_FUNC_EXTERN( HB_ZEBRA_GETERROR );
HB_FUNC( __HBEXTERN__HBZEBRA__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBZEBRA )
{ "HB_ZEBRA_CREATE_CODABAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_CODABAR )}, NULL },
{ "HB_ZEBRA_CREATE_CODE11", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_CODE11 )}, NULL },
{ "HB_ZEBRA_CREATE_CODE128", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_CODE128 )}, NULL },
{ "HB_ZEBRA_CREATE_CODE39", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_CODE39 )}, NULL },
{ "HB_ZEBRA_CREATE_CODE93", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_CODE93 )}, NULL },
{ "HB_ZEBRA_CREATE_DATAMATRIX", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_DATAMATRIX )}, NULL },
{ "HB_ZEBRA_CREATE_EAN13", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_EAN13 )}, NULL },
{ "HB_ZEBRA_CREATE_EAN8", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_EAN8 )}, NULL },
{ "HB_ZEBRA_CREATE_ITF", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_ITF )}, NULL },
{ "HB_ZEBRA_CREATE_MSI", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_MSI )}, NULL },
{ "HB_ZEBRA_CREATE_PDF417", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_PDF417 )}, NULL },
{ "HB_ZEBRA_CREATE_QRCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_QRCODE )}, NULL },
{ "HB_ZEBRA_CREATE_UPCA", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_UPCA )}, NULL },
{ "HB_ZEBRA_CREATE_UPCE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_CREATE_UPCE )}, NULL },
{ "HB_ZEBRA_DESTROY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_DESTROY )}, NULL },
{ "HB_ZEBRA_DRAW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_DRAW )}, NULL },
{ "HB_ZEBRA_GETCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_GETCODE )}, NULL },
{ "HB_ZEBRA_GETERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZEBRA_GETERROR )}, NULL },
{ "__HBEXTERN__HBZEBRA__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBZEBRA__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBZEBRA, "hbzebra\\hbzebra.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBZEBRA
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBZEBRA )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBZEBRA__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

