/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (64-bit)
 * Generated C source from "..\contrib\hbct\hbct.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( ACOS );
HB_FUNC_EXTERN( ADDASCII );
HB_FUNC_EXTERN( ADDMONTH );
HB_FUNC_EXTERN( AFTERATNUM );
HB_FUNC_EXTERN( ALLOFREE );
HB_FUNC_EXTERN( ASCIISUM );
HB_FUNC_EXTERN( ASCPOS );
HB_FUNC_EXTERN( ASIN );
HB_FUNC_EXTERN( ATADJUST );
HB_FUNC_EXTERN( ATAN );
HB_FUNC_EXTERN( ATN2 );
HB_FUNC_EXTERN( ATNUM );
HB_FUNC_EXTERN( ATREPL );
HB_FUNC_EXTERN( ATTOKEN );
HB_FUNC_EXTERN( BEFORATNUM );
HB_FUNC_EXTERN( BITTOC );
HB_FUNC_EXTERN( BLANK );
HB_FUNC_EXTERN( BOM );
HB_FUNC_EXTERN( BOQ );
HB_FUNC_EXTERN( BOY );
HB_FUNC_EXTERN( CEILING );
HB_FUNC_EXTERN( CELSIUS );
HB_FUNC_EXTERN( CENTER );
HB_FUNC_EXTERN( CHARADD );
HB_FUNC_EXTERN( CHARAND );
HB_FUNC_EXTERN( CHAREVEN );
HB_FUNC_EXTERN( CHARHIST );
HB_FUNC_EXTERN( CHARLIST );
HB_FUNC_EXTERN( CHARMIRR );
HB_FUNC_EXTERN( CHARMIX );
HB_FUNC_EXTERN( CHARNOLIST );
HB_FUNC_EXTERN( CHARNOT );
HB_FUNC_EXTERN( CHARODD );
HB_FUNC_EXTERN( CHARONE );
HB_FUNC_EXTERN( CHARONLY );
HB_FUNC_EXTERN( CHAROR );
HB_FUNC_EXTERN( CHARPACK );
HB_FUNC_EXTERN( CHARPIX );
HB_FUNC_EXTERN( CHARRELA );
HB_FUNC_EXTERN( CHARRELREP );
HB_FUNC_EXTERN( CHARREM );
HB_FUNC_EXTERN( CHARREPL );
HB_FUNC_EXTERN( CHARRLL );
HB_FUNC_EXTERN( CHARRLR );
HB_FUNC_EXTERN( CHARSHL );
HB_FUNC_EXTERN( CHARSHR );
HB_FUNC_EXTERN( CHARSLIST );
HB_FUNC_EXTERN( CHARSORT );
HB_FUNC_EXTERN( CHARSPREAD );
HB_FUNC_EXTERN( CHARSUB );
HB_FUNC_EXTERN( CHARSWAP );
HB_FUNC_EXTERN( CHARUNPACK );
HB_FUNC_EXTERN( CHARWIN );
HB_FUNC_EXTERN( CHARXOR );
HB_FUNC_EXTERN( CHECKSUM );
HB_FUNC_EXTERN( CLEARBIT );
HB_FUNC_EXTERN( CLEAREOL );
HB_FUNC_EXTERN( CLEARSLOW );
HB_FUNC_EXTERN( CLEARWIN );
HB_FUNC_EXTERN( CLEOL );
HB_FUNC_EXTERN( CLWIN );
HB_FUNC_EXTERN( COLORREPL );
HB_FUNC_EXTERN( COLORTON );
HB_FUNC_EXTERN( COLORWIN );
HB_FUNC_EXTERN( COMPLEMENT );
HB_FUNC_EXTERN( COM_BREAK );
HB_FUNC_EXTERN( COM_CLOSE );
HB_FUNC_EXTERN( COM_COUNT );
HB_FUNC_EXTERN( COM_CRC );
HB_FUNC_EXTERN( COM_CTS );
HB_FUNC_EXTERN( COM_DCD );
HB_FUNC_EXTERN( COM_DEVNAME );
HB_FUNC_EXTERN( COM_DOSCON );
HB_FUNC_EXTERN( COM_DSR );
HB_FUNC_EXTERN( COM_DTR );
HB_FUNC_EXTERN( COM_ERRCHR );
HB_FUNC_EXTERN( COM_EVENT );
HB_FUNC_EXTERN( COM_FLUSH );
HB_FUNC_EXTERN( COM_GETIO );
HB_FUNC_EXTERN( COM_GETIRQ );
HB_FUNC_EXTERN( COM_HARD );
HB_FUNC_EXTERN( COM_INIT );
HB_FUNC_EXTERN( COM_KEY );
HB_FUNC_EXTERN( COM_LSR );
HB_FUNC_EXTERN( COM_MCR );
HB_FUNC_EXTERN( COM_MSR );
HB_FUNC_EXTERN( COM_NUM );
HB_FUNC_EXTERN( COM_OPEN );
HB_FUNC_EXTERN( COM_READ );
HB_FUNC_EXTERN( COM_REMOTE );
HB_FUNC_EXTERN( COM_RING );
HB_FUNC_EXTERN( COM_RTS );
HB_FUNC_EXTERN( COM_SCOUNT );
HB_FUNC_EXTERN( COM_SEND );
HB_FUNC_EXTERN( COM_SETIO );
HB_FUNC_EXTERN( COM_SETIRQ );
HB_FUNC_EXTERN( COM_SFLUSH );
HB_FUNC_EXTERN( COM_SKEY );
HB_FUNC_EXTERN( COM_SMODE );
HB_FUNC_EXTERN( COM_SOFT );
HB_FUNC_EXTERN( COM_SOFT_R );
HB_FUNC_EXTERN( COM_SOFT_S );
HB_FUNC_EXTERN( COS );
HB_FUNC_EXTERN( COSH );
HB_FUNC_EXTERN( COT );
HB_FUNC_EXTERN( COUNTGETS );
HB_FUNC_EXTERN( COUNTLEFT );
HB_FUNC_EXTERN( COUNTRIGHT );
HB_FUNC_EXTERN( CRYPT );
HB_FUNC_EXTERN( CSETARGERR );
HB_FUNC_EXTERN( CSETATMUPA );
HB_FUNC_EXTERN( CSETCENT );
HB_FUNC_EXTERN( CSETCURS );
HB_FUNC_EXTERN( CSETKEY );
HB_FUNC_EXTERN( CSETREF );
HB_FUNC_EXTERN( CSETSAFETY );
HB_FUNC_EXTERN( CTCEXIT );
HB_FUNC_EXTERN( CTCINIT );
HB_FUNC_EXTERN( CTEXIT );
HB_FUNC_EXTERN( CTINIT );
HB_FUNC_EXTERN( CTOBIT );
HB_FUNC_EXTERN( CTODOW );
HB_FUNC_EXTERN( CTOF );
HB_FUNC_EXTERN( CTOMONTH );
HB_FUNC_EXTERN( CTON );
HB_FUNC_EXTERN( CTWINIT );
HB_FUNC_EXTERN( CTWLASTKEY );
HB_FUNC_EXTERN( CURRENTGET );
HB_FUNC_EXTERN( DAYSINMONTH );
HB_FUNC_EXTERN( DAYSTOMONTH );
HB_FUNC_EXTERN( DBFSIZE );
HB_FUNC_EXTERN( DELETEFILE );
HB_FUNC_EXTERN( DIRMAKE );
HB_FUNC_EXTERN( DIRNAME );
HB_FUNC_EXTERN( DMY );
HB_FUNC_EXTERN( DOSPARAM );
HB_FUNC_EXTERN( DOY );
HB_FUNC_EXTERN( DRIVETYPE );
HB_FUNC_EXTERN( DSETKBIOS );
HB_FUNC_EXTERN( DTOR );
HB_FUNC_EXTERN( ENHANCED );
HB_FUNC_EXTERN( ENVPARAM );
HB_FUNC_EXTERN( EOM );
HB_FUNC_EXTERN( EOQ );
HB_FUNC_EXTERN( EOY );
HB_FUNC_EXTERN( EXENAME );
HB_FUNC_EXTERN( EXPAND );
HB_FUNC_EXTERN( EXPONENT );
HB_FUNC_EXTERN( FACT );
HB_FUNC_EXTERN( FAHRENHEIT );
HB_FUNC_EXTERN( FIELDDECI );
HB_FUNC_EXTERN( FIELDNUM );
HB_FUNC_EXTERN( FIELDSIZE );
HB_FUNC_EXTERN( FILEAPPEND );
HB_FUNC_EXTERN( FILEATTR );
HB_FUNC_EXTERN( FILECCLOSE );
HB_FUNC_EXTERN( FILECCONT );
HB_FUNC_EXTERN( FILECDATI );
HB_FUNC_EXTERN( FILECOPEN );
HB_FUNC_EXTERN( FILECOPY );
HB_FUNC_EXTERN( FILEDATE );
HB_FUNC_EXTERN( FILEDELETE );
HB_FUNC_EXTERN( FILEMOVE );
HB_FUNC_EXTERN( FILESCREEN );
HB_FUNC_EXTERN( FILESEEK );
HB_FUNC_EXTERN( FILESIZE );
HB_FUNC_EXTERN( FILESMAX );
HB_FUNC_EXTERN( FILESTR );
HB_FUNC_EXTERN( FILETIME );
HB_FUNC_EXTERN( FLOOR );
HB_FUNC_EXTERN( FTOC );
HB_FUNC_EXTERN( FV );
HB_FUNC_EXTERN( GETCLEARA );
HB_FUNC_EXTERN( GETCLEARB );
HB_FUNC_EXTERN( GETFLDCOL );
HB_FUNC_EXTERN( GETFLDROW );
HB_FUNC_EXTERN( GETFLDVAR );
HB_FUNC_EXTERN( GETINPUT );
HB_FUNC_EXTERN( GETKXLAT );
HB_FUNC_EXTERN( GETKXTAB );
HB_FUNC_EXTERN( GETPREC );
HB_FUNC_EXTERN( GETSECRET );
HB_FUNC_EXTERN( HBCT_GETKXLAT );
HB_FUNC_EXTERN( HBCT_GETKXTAB );
HB_FUNC_EXTERN( HBCT_MAXCOL );
HB_FUNC_EXTERN( HBCT_MAXROW );
HB_FUNC_EXTERN( HBCT_SETKXLAT );
HB_FUNC_EXTERN( HBCT_SETKXTAB );
HB_FUNC_EXTERN( INFINITY );
HB_FUNC_EXTERN( INTNEG );
HB_FUNC_EXTERN( INTPOS );
HB_FUNC_EXTERN( INVERTATTR );
HB_FUNC_EXTERN( INVERTWIN );
HB_FUNC_EXTERN( ISAT );
HB_FUNC_EXTERN( ISBIT );
HB_FUNC_EXTERN( ISLEAP );
HB_FUNC_EXTERN( JUSTLEFT );
HB_FUNC_EXTERN( JUSTRIGHT );
HB_FUNC_EXTERN( KBDSTAT );
HB_FUNC_EXTERN( KEYSEC );
HB_FUNC_EXTERN( KEYTIME );
HB_FUNC_EXTERN( KSETCAPS );
HB_FUNC_EXTERN( KSETINS );
HB_FUNC_EXTERN( KSETNUM );
HB_FUNC_EXTERN( KSETSCROLL );
HB_FUNC_EXTERN( LASTDAYOM );
HB_FUNC_EXTERN( LIKE );
HB_FUNC_EXTERN( LOG10 );
HB_FUNC_EXTERN( LTOC );
HB_FUNC_EXTERN( LTON );
HB_FUNC_EXTERN( MANTISSA );
HB_FUNC_EXTERN( MAXLINE );
HB_FUNC_EXTERN( MDY );
HB_FUNC_EXTERN( MILLISEC );
HB_FUNC_EXTERN( NETCANCEL );
HB_FUNC_EXTERN( NETDISK );
HB_FUNC_EXTERN( NETPRINTER );
HB_FUNC_EXTERN( NETREDIR );
HB_FUNC_EXTERN( NETRMTNAME );
HB_FUNC_EXTERN( NETWORK );
HB_FUNC_EXTERN( NNETWORK );
HB_FUNC_EXTERN( NTOC );
HB_FUNC_EXTERN( NTOCDOW );
HB_FUNC_EXTERN( NTOCMONTH );
HB_FUNC_EXTERN( NTOCOLOR );
HB_FUNC_EXTERN( NUL );
HB_FUNC_EXTERN( NUMAND );
HB_FUNC_EXTERN( NUMAT );
HB_FUNC_EXTERN( NUMCOUNT );
HB_FUNC_EXTERN( NUMDISKL );
HB_FUNC_EXTERN( NUMHIGH );
HB_FUNC_EXTERN( NUMLINE );
HB_FUNC_EXTERN( NUMLOW );
HB_FUNC_EXTERN( NUMMIRR );
HB_FUNC_EXTERN( NUMNOT );
HB_FUNC_EXTERN( NUMOR );
HB_FUNC_EXTERN( NUMROL );
HB_FUNC_EXTERN( NUMTOKEN );
HB_FUNC_EXTERN( NUMXOR );
HB_FUNC_EXTERN( PADLEFT );
HB_FUNC_EXTERN( PADRIGHT );
HB_FUNC_EXTERN( PAYMENT );
HB_FUNC_EXTERN( PERIODS );
HB_FUNC_EXTERN( PI );
HB_FUNC_EXTERN( POSALPHA );
HB_FUNC_EXTERN( POSCHAR );
HB_FUNC_EXTERN( POSDEL );
HB_FUNC_EXTERN( POSDIFF );
HB_FUNC_EXTERN( POSEQUAL );
HB_FUNC_EXTERN( POSINS );
HB_FUNC_EXTERN( POSLOWER );
HB_FUNC_EXTERN( POSRANGE );
HB_FUNC_EXTERN( POSREPL );
HB_FUNC_EXTERN( POSUPPER );
HB_FUNC_EXTERN( PRINTREADY );
HB_FUNC_EXTERN( PRINTSEND );
HB_FUNC_EXTERN( PRINTSTAT );
HB_FUNC_EXTERN( PV );
HB_FUNC_EXTERN( QUARTER );
HB_FUNC_EXTERN( RAND );
HB_FUNC_EXTERN( RANDOM );
HB_FUNC_EXTERN( RANGEREM );
HB_FUNC_EXTERN( RANGEREPL );
HB_FUNC_EXTERN( RATE );
HB_FUNC_EXTERN( REMALL );
HB_FUNC_EXTERN( REMLEFT );
HB_FUNC_EXTERN( REMRIGHT );
HB_FUNC_EXTERN( RENAMEFILE );
HB_FUNC_EXTERN( REPLALL );
HB_FUNC_EXTERN( REPLLEFT );
HB_FUNC_EXTERN( REPLRIGHT );
HB_FUNC_EXTERN( RESTCURSOR );
HB_FUNC_EXTERN( RESTGETS );
HB_FUNC_EXTERN( RESTSETKEY );
HB_FUNC_EXTERN( RESTTOKEN );
HB_FUNC_EXTERN( RTOD );
HB_FUNC_EXTERN( SAVECURSOR );
HB_FUNC_EXTERN( SAVEGETS );
HB_FUNC_EXTERN( SAVESETKEY );
HB_FUNC_EXTERN( SAVETOKEN );
HB_FUNC_EXTERN( SAYDOWN );
HB_FUNC_EXTERN( SAYMOVEIN );
HB_FUNC_EXTERN( SAYSCREEN );
HB_FUNC_EXTERN( SAYSPREAD );
HB_FUNC_EXTERN( SCREENATTR );
HB_FUNC_EXTERN( SCREENFILE );
HB_FUNC_EXTERN( SCREENMARK );
HB_FUNC_EXTERN( SCREENMIX );
HB_FUNC_EXTERN( SCREENSTR );
HB_FUNC_EXTERN( SCREENTEXT );
HB_FUNC_EXTERN( SECTOTIME );
HB_FUNC_EXTERN( SETATLIKE );
HB_FUNC_EXTERN( SETBIT );
HB_FUNC_EXTERN( SETCLEARA );
HB_FUNC_EXTERN( SETCLEARB );
HB_FUNC_EXTERN( SETDATE );
HB_FUNC_EXTERN( SETFATTR );
HB_FUNC_EXTERN( SETFCREATE );
HB_FUNC_EXTERN( SETFDATI );
HB_FUNC_EXTERN( SETFONT );
HB_FUNC_EXTERN( SETKXLAT );
HB_FUNC_EXTERN( SETKXTAB );
HB_FUNC_EXTERN( SETLASTKEY );
HB_FUNC_EXTERN( SETPREC );
HB_FUNC_EXTERN( SETRC );
HB_FUNC_EXTERN( SETTIME );
HB_FUNC_EXTERN( SHOWTIME );
HB_FUNC_EXTERN( SIGN );
HB_FUNC_EXTERN( SIN );
HB_FUNC_EXTERN( SINH );
HB_FUNC_EXTERN( STANDARD );
HB_FUNC_EXTERN( STRDIFF );
HB_FUNC_EXTERN( STRFILE );
HB_FUNC_EXTERN( STRSCREEN );
HB_FUNC_EXTERN( STRSWAP );
HB_FUNC_EXTERN( TABEXPAND );
HB_FUNC_EXTERN( TABPACK );
HB_FUNC_EXTERN( TAN );
HB_FUNC_EXTERN( TANH );
HB_FUNC_EXTERN( TEMPFILE );
HB_FUNC_EXTERN( TIMETOSEC );
HB_FUNC_EXTERN( TIMEVALID );
HB_FUNC_EXTERN( TOKEN );
HB_FUNC_EXTERN( TOKENAT );
HB_FUNC_EXTERN( TOKENEND );
HB_FUNC_EXTERN( TOKENEXIT );
HB_FUNC_EXTERN( TOKENINIT );
HB_FUNC_EXTERN( TOKENLOWER );
HB_FUNC_EXTERN( TOKENNEXT );
HB_FUNC_EXTERN( TOKENNUM );
HB_FUNC_EXTERN( TOKENSEP );
HB_FUNC_EXTERN( TOKENUPPER );
HB_FUNC_EXTERN( TOOLVER );
HB_FUNC_EXTERN( TRUENAME );
HB_FUNC_EXTERN( UNSELECTED );
HB_FUNC_EXTERN( UNTEXTWIN );
HB_FUNC_EXTERN( VALPOS );
HB_FUNC_EXTERN( VGAPALETTE );
HB_FUNC_EXTERN( VIDEOTYPE );
HB_FUNC_EXTERN( VOLSERIAL );
HB_FUNC_EXTERN( VOLUME );
HB_FUNC_EXTERN( WACLOSE );
HB_FUNC_EXTERN( WAITPERIOD );
HB_FUNC_EXTERN( WALIAS );
HB_FUNC_EXTERN( WBOARD );
HB_FUNC_EXTERN( WBOX );
HB_FUNC_EXTERN( WCENTER );
HB_FUNC_EXTERN( WCLOSE );
HB_FUNC_EXTERN( WCOL );
HB_FUNC_EXTERN( WEEK );
HB_FUNC_EXTERN( WFCOL );
HB_FUNC_EXTERN( WFLASTCOL );
HB_FUNC_EXTERN( WFLASTROW );
HB_FUNC_EXTERN( WFORMAT );
HB_FUNC_EXTERN( WFROW );
HB_FUNC_EXTERN( WHIDE );
HB_FUNC_EXTERN( WLASTCOL );
HB_FUNC_EXTERN( WLASTROW );
HB_FUNC_EXTERN( WLEVEL );
HB_FUNC_EXTERN( WLIST );
HB_FUNC_EXTERN( WMODE );
HB_FUNC_EXTERN( WMOVE );
HB_FUNC_EXTERN( WNUM );
HB_FUNC_EXTERN( WOM );
HB_FUNC_EXTERN( WOPEN );
HB_FUNC_EXTERN( WORDONE );
HB_FUNC_EXTERN( WORDONLY );
HB_FUNC_EXTERN( WORDREM );
HB_FUNC_EXTERN( WORDREPL );
HB_FUNC_EXTERN( WORDSWAP );
HB_FUNC_EXTERN( WORDTOCHAR );
HB_FUNC_EXTERN( WROW );
HB_FUNC_EXTERN( WSELECT );
HB_FUNC_EXTERN( WSETMOVE );
HB_FUNC_EXTERN( WSETSHADOW );
HB_FUNC_EXTERN( WSHADOW );
HB_FUNC_EXTERN( WSHOW );
HB_FUNC_EXTERN( WSTEP );
HB_FUNC_EXTERN( XMOBLOCK );
HB_FUNC_EXTERN( XMOCHECK );
HB_FUNC_EXTERN( XTOC );
HB_FUNC_EXTERN( ZEROINSERT );
HB_FUNC_EXTERN( ZEROREMOVE );
HB_FUNC_EXTERN( _WSTACK );
HB_FUNC_EXTERN( __HBCT_DSPTIME );
HB_FUNC_EXTERN( __HBCT_KEY_C_TO_N );
HB_FUNC_EXTERN( __HBCT_KEY_N_TO_C );
HB_FUNC( __HBEXTERN__HBCT__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBCT )
{ "ACOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ACOS )}, NULL },
{ "ADDASCII", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADDASCII )}, NULL },
{ "ADDMONTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADDMONTH )}, NULL },
{ "AFTERATNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( AFTERATNUM )}, NULL },
{ "ALLOFREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLOFREE )}, NULL },
{ "ASCIISUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASCIISUM )}, NULL },
{ "ASCPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASCPOS )}, NULL },
{ "ASIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASIN )}, NULL },
{ "ATADJUST", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATADJUST )}, NULL },
{ "ATAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATAN )}, NULL },
{ "ATN2", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATN2 )}, NULL },
{ "ATNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATNUM )}, NULL },
{ "ATREPL", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATREPL )}, NULL },
{ "ATTOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( ATTOKEN )}, NULL },
{ "BEFORATNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( BEFORATNUM )}, NULL },
{ "BITTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( BITTOC )}, NULL },
{ "BLANK", {HB_FS_PUBLIC}, {HB_FUNCNAME( BLANK )}, NULL },
{ "BOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOM )}, NULL },
{ "BOQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOQ )}, NULL },
{ "BOY", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOY )}, NULL },
{ "CEILING", {HB_FS_PUBLIC}, {HB_FUNCNAME( CEILING )}, NULL },
{ "CELSIUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( CELSIUS )}, NULL },
{ "CENTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( CENTER )}, NULL },
{ "CHARADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARADD )}, NULL },
{ "CHARAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARAND )}, NULL },
{ "CHAREVEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHAREVEN )}, NULL },
{ "CHARHIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARHIST )}, NULL },
{ "CHARLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARLIST )}, NULL },
{ "CHARMIRR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARMIRR )}, NULL },
{ "CHARMIX", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARMIX )}, NULL },
{ "CHARNOLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARNOLIST )}, NULL },
{ "CHARNOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARNOT )}, NULL },
{ "CHARODD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARODD )}, NULL },
{ "CHARONE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARONE )}, NULL },
{ "CHARONLY", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARONLY )}, NULL },
{ "CHAROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHAROR )}, NULL },
{ "CHARPACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARPACK )}, NULL },
{ "CHARPIX", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARPIX )}, NULL },
{ "CHARRELA", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARRELA )}, NULL },
{ "CHARRELREP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARRELREP )}, NULL },
{ "CHARREM", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARREM )}, NULL },
{ "CHARREPL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARREPL )}, NULL },
{ "CHARRLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARRLL )}, NULL },
{ "CHARRLR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARRLR )}, NULL },
{ "CHARSHL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSHL )}, NULL },
{ "CHARSHR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSHR )}, NULL },
{ "CHARSLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSLIST )}, NULL },
{ "CHARSORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSORT )}, NULL },
{ "CHARSPREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSPREAD )}, NULL },
{ "CHARSUB", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSUB )}, NULL },
{ "CHARSWAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARSWAP )}, NULL },
{ "CHARUNPACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARUNPACK )}, NULL },
{ "CHARWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARWIN )}, NULL },
{ "CHARXOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHARXOR )}, NULL },
{ "CHECKSUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( CHECKSUM )}, NULL },
{ "CLEARBIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLEARBIT )}, NULL },
{ "CLEAREOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLEAREOL )}, NULL },
{ "CLEARSLOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLEARSLOW )}, NULL },
{ "CLEARWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLEARWIN )}, NULL },
{ "CLEOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLEOL )}, NULL },
{ "CLWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLWIN )}, NULL },
{ "COLORREPL", {HB_FS_PUBLIC}, {HB_FUNCNAME( COLORREPL )}, NULL },
{ "COLORTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( COLORTON )}, NULL },
{ "COLORWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( COLORWIN )}, NULL },
{ "COMPLEMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COMPLEMENT )}, NULL },
{ "COM_BREAK", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_BREAK )}, NULL },
{ "COM_CLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_CLOSE )}, NULL },
{ "COM_COUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_COUNT )}, NULL },
{ "COM_CRC", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_CRC )}, NULL },
{ "COM_CTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_CTS )}, NULL },
{ "COM_DCD", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_DCD )}, NULL },
{ "COM_DEVNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_DEVNAME )}, NULL },
{ "COM_DOSCON", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_DOSCON )}, NULL },
{ "COM_DSR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_DSR )}, NULL },
{ "COM_DTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_DTR )}, NULL },
{ "COM_ERRCHR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_ERRCHR )}, NULL },
{ "COM_EVENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_EVENT )}, NULL },
{ "COM_FLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_FLUSH )}, NULL },
{ "COM_GETIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_GETIO )}, NULL },
{ "COM_GETIRQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_GETIRQ )}, NULL },
{ "COM_HARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_HARD )}, NULL },
{ "COM_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_INIT )}, NULL },
{ "COM_KEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_KEY )}, NULL },
{ "COM_LSR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_LSR )}, NULL },
{ "COM_MCR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_MCR )}, NULL },
{ "COM_MSR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_MSR )}, NULL },
{ "COM_NUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_NUM )}, NULL },
{ "COM_OPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_OPEN )}, NULL },
{ "COM_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_READ )}, NULL },
{ "COM_REMOTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_REMOTE )}, NULL },
{ "COM_RING", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_RING )}, NULL },
{ "COM_RTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_RTS )}, NULL },
{ "COM_SCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SCOUNT )}, NULL },
{ "COM_SEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SEND )}, NULL },
{ "COM_SETIO", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SETIO )}, NULL },
{ "COM_SETIRQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SETIRQ )}, NULL },
{ "COM_SFLUSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SFLUSH )}, NULL },
{ "COM_SKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SKEY )}, NULL },
{ "COM_SMODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SMODE )}, NULL },
{ "COM_SOFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SOFT )}, NULL },
{ "COM_SOFT_R", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SOFT_R )}, NULL },
{ "COM_SOFT_S", {HB_FS_PUBLIC}, {HB_FUNCNAME( COM_SOFT_S )}, NULL },
{ "COS", {HB_FS_PUBLIC}, {HB_FUNCNAME( COS )}, NULL },
{ "COSH", {HB_FS_PUBLIC}, {HB_FUNCNAME( COSH )}, NULL },
{ "COT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COT )}, NULL },
{ "COUNTGETS", {HB_FS_PUBLIC}, {HB_FUNCNAME( COUNTGETS )}, NULL },
{ "COUNTLEFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COUNTLEFT )}, NULL },
{ "COUNTRIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( COUNTRIGHT )}, NULL },
{ "CRYPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CRYPT )}, NULL },
{ "CSETARGERR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETARGERR )}, NULL },
{ "CSETATMUPA", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETATMUPA )}, NULL },
{ "CSETCENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETCENT )}, NULL },
{ "CSETCURS", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETCURS )}, NULL },
{ "CSETKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETKEY )}, NULL },
{ "CSETREF", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETREF )}, NULL },
{ "CSETSAFETY", {HB_FS_PUBLIC}, {HB_FUNCNAME( CSETSAFETY )}, NULL },
{ "CTCEXIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTCEXIT )}, NULL },
{ "CTCINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTCINIT )}, NULL },
{ "CTEXIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTEXIT )}, NULL },
{ "CTINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTINIT )}, NULL },
{ "CTOBIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOBIT )}, NULL },
{ "CTODOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTODOW )}, NULL },
{ "CTOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOF )}, NULL },
{ "CTOMONTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOMONTH )}, NULL },
{ "CTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTON )}, NULL },
{ "CTWINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTWINIT )}, NULL },
{ "CTWLASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTWLASTKEY )}, NULL },
{ "CURRENTGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURRENTGET )}, NULL },
{ "DAYSINMONTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( DAYSINMONTH )}, NULL },
{ "DAYSTOMONTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( DAYSTOMONTH )}, NULL },
{ "DBFSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBFSIZE )}, NULL },
{ "DELETEFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DELETEFILE )}, NULL },
{ "DIRMAKE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DIRMAKE )}, NULL },
{ "DIRNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( DIRNAME )}, NULL },
{ "DMY", {HB_FS_PUBLIC}, {HB_FUNCNAME( DMY )}, NULL },
{ "DOSPARAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( DOSPARAM )}, NULL },
{ "DOY", {HB_FS_PUBLIC}, {HB_FUNCNAME( DOY )}, NULL },
{ "DRIVETYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DRIVETYPE )}, NULL },
{ "DSETKBIOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( DSETKBIOS )}, NULL },
{ "DTOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( DTOR )}, NULL },
{ "ENHANCED", {HB_FS_PUBLIC}, {HB_FUNCNAME( ENHANCED )}, NULL },
{ "ENVPARAM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ENVPARAM )}, NULL },
{ "EOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOM )}, NULL },
{ "EOQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOQ )}, NULL },
{ "EOY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOY )}, NULL },
{ "EXENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXENAME )}, NULL },
{ "EXPAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPAND )}, NULL },
{ "EXPONENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPONENT )}, NULL },
{ "FACT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FACT )}, NULL },
{ "FAHRENHEIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FAHRENHEIT )}, NULL },
{ "FIELDDECI", {HB_FS_PUBLIC}, {HB_FUNCNAME( FIELDDECI )}, NULL },
{ "FIELDNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( FIELDNUM )}, NULL },
{ "FIELDSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FIELDSIZE )}, NULL },
{ "FILEAPPEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEAPPEND )}, NULL },
{ "FILEATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEATTR )}, NULL },
{ "FILECCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILECCLOSE )}, NULL },
{ "FILECCONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILECCONT )}, NULL },
{ "FILECDATI", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILECDATI )}, NULL },
{ "FILECOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILECOPEN )}, NULL },
{ "FILECOPY", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILECOPY )}, NULL },
{ "FILEDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEDATE )}, NULL },
{ "FILEDELETE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEDELETE )}, NULL },
{ "FILEMOVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILEMOVE )}, NULL },
{ "FILESCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILESCREEN )}, NULL },
{ "FILESEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILESEEK )}, NULL },
{ "FILESIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILESIZE )}, NULL },
{ "FILESMAX", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILESMAX )}, NULL },
{ "FILESTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILESTR )}, NULL },
{ "FILETIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILETIME )}, NULL },
{ "FLOOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FLOOR )}, NULL },
{ "FTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( FTOC )}, NULL },
{ "FV", {HB_FS_PUBLIC}, {HB_FUNCNAME( FV )}, NULL },
{ "GETCLEARA", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETCLEARA )}, NULL },
{ "GETCLEARB", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETCLEARB )}, NULL },
{ "GETFLDCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETFLDCOL )}, NULL },
{ "GETFLDROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETFLDROW )}, NULL },
{ "GETFLDVAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETFLDVAR )}, NULL },
{ "GETINPUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETINPUT )}, NULL },
{ "GETKXLAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETKXLAT )}, NULL },
{ "GETKXTAB", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETKXTAB )}, NULL },
{ "GETPREC", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETPREC )}, NULL },
{ "GETSECRET", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETSECRET )}, NULL },
{ "HBCT_GETKXLAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCT_GETKXLAT )}, NULL },
{ "HBCT_GETKXTAB", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCT_GETKXTAB )}, NULL },
{ "HBCT_MAXCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCT_MAXCOL )}, NULL },
{ "HBCT_MAXROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCT_MAXROW )}, NULL },
{ "HBCT_SETKXLAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCT_SETKXLAT )}, NULL },
{ "HBCT_SETKXTAB", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCT_SETKXTAB )}, NULL },
{ "INFINITY", {HB_FS_PUBLIC}, {HB_FUNCNAME( INFINITY )}, NULL },
{ "INTNEG", {HB_FS_PUBLIC}, {HB_FUNCNAME( INTNEG )}, NULL },
{ "INTPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( INTPOS )}, NULL },
{ "INVERTATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( INVERTATTR )}, NULL },
{ "INVERTWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( INVERTWIN )}, NULL },
{ "ISAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISAT )}, NULL },
{ "ISBIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISBIT )}, NULL },
{ "ISLEAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISLEAP )}, NULL },
{ "JUSTLEFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( JUSTLEFT )}, NULL },
{ "JUSTRIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( JUSTRIGHT )}, NULL },
{ "KBDSTAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( KBDSTAT )}, NULL },
{ "KEYSEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( KEYSEC )}, NULL },
{ "KEYTIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( KEYTIME )}, NULL },
{ "KSETCAPS", {HB_FS_PUBLIC}, {HB_FUNCNAME( KSETCAPS )}, NULL },
{ "KSETINS", {HB_FS_PUBLIC}, {HB_FUNCNAME( KSETINS )}, NULL },
{ "KSETNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( KSETNUM )}, NULL },
{ "KSETSCROLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( KSETSCROLL )}, NULL },
{ "LASTDAYOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( LASTDAYOM )}, NULL },
{ "LIKE", {HB_FS_PUBLIC}, {HB_FUNCNAME( LIKE )}, NULL },
{ "LOG10", {HB_FS_PUBLIC}, {HB_FUNCNAME( LOG10 )}, NULL },
{ "LTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( LTOC )}, NULL },
{ "LTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( LTON )}, NULL },
{ "MANTISSA", {HB_FS_PUBLIC}, {HB_FUNCNAME( MANTISSA )}, NULL },
{ "MAXLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MAXLINE )}, NULL },
{ "MDY", {HB_FS_PUBLIC}, {HB_FUNCNAME( MDY )}, NULL },
{ "MILLISEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( MILLISEC )}, NULL },
{ "NETCANCEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETCANCEL )}, NULL },
{ "NETDISK", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETDISK )}, NULL },
{ "NETPRINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETPRINTER )}, NULL },
{ "NETREDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETREDIR )}, NULL },
{ "NETRMTNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETRMTNAME )}, NULL },
{ "NETWORK", {HB_FS_PUBLIC}, {HB_FUNCNAME( NETWORK )}, NULL },
{ "NNETWORK", {HB_FS_PUBLIC}, {HB_FUNCNAME( NNETWORK )}, NULL },
{ "NTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( NTOC )}, NULL },
{ "NTOCDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( NTOCDOW )}, NULL },
{ "NTOCMONTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( NTOCMONTH )}, NULL },
{ "NTOCOLOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NTOCOLOR )}, NULL },
{ "NUL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUL )}, NULL },
{ "NUMAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMAND )}, NULL },
{ "NUMAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMAT )}, NULL },
{ "NUMCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMCOUNT )}, NULL },
{ "NUMDISKL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMDISKL )}, NULL },
{ "NUMHIGH", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMHIGH )}, NULL },
{ "NUMLINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMLINE )}, NULL },
{ "NUMLOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMLOW )}, NULL },
{ "NUMMIRR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMMIRR )}, NULL },
{ "NUMNOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMNOT )}, NULL },
{ "NUMOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMOR )}, NULL },
{ "NUMROL", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMROL )}, NULL },
{ "NUMTOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMTOKEN )}, NULL },
{ "NUMXOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMXOR )}, NULL },
{ "PADLEFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PADLEFT )}, NULL },
{ "PADRIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PADRIGHT )}, NULL },
{ "PAYMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PAYMENT )}, NULL },
{ "PERIODS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PERIODS )}, NULL },
{ "PI", {HB_FS_PUBLIC}, {HB_FUNCNAME( PI )}, NULL },
{ "POSALPHA", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSALPHA )}, NULL },
{ "POSCHAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSCHAR )}, NULL },
{ "POSDEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSDEL )}, NULL },
{ "POSDIFF", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSDIFF )}, NULL },
{ "POSEQUAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSEQUAL )}, NULL },
{ "POSINS", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSINS )}, NULL },
{ "POSLOWER", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSLOWER )}, NULL },
{ "POSRANGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSRANGE )}, NULL },
{ "POSREPL", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSREPL )}, NULL },
{ "POSUPPER", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSUPPER )}, NULL },
{ "PRINTREADY", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTREADY )}, NULL },
{ "PRINTSEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTSEND )}, NULL },
{ "PRINTSTAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PRINTSTAT )}, NULL },
{ "PV", {HB_FS_PUBLIC}, {HB_FUNCNAME( PV )}, NULL },
{ "QUARTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( QUARTER )}, NULL },
{ "RAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( RAND )}, NULL },
{ "RANDOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( RANDOM )}, NULL },
{ "RANGEREM", {HB_FS_PUBLIC}, {HB_FUNCNAME( RANGEREM )}, NULL },
{ "RANGEREPL", {HB_FS_PUBLIC}, {HB_FUNCNAME( RANGEREPL )}, NULL },
{ "RATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( RATE )}, NULL },
{ "REMALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( REMALL )}, NULL },
{ "REMLEFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( REMLEFT )}, NULL },
{ "REMRIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( REMRIGHT )}, NULL },
{ "RENAMEFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( RENAMEFILE )}, NULL },
{ "REPLALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLALL )}, NULL },
{ "REPLLEFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLLEFT )}, NULL },
{ "REPLRIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLRIGHT )}, NULL },
{ "RESTCURSOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESTCURSOR )}, NULL },
{ "RESTGETS", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESTGETS )}, NULL },
{ "RESTSETKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESTSETKEY )}, NULL },
{ "RESTTOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESTTOKEN )}, NULL },
{ "RTOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( RTOD )}, NULL },
{ "SAVECURSOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVECURSOR )}, NULL },
{ "SAVEGETS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVEGETS )}, NULL },
{ "SAVESETKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVESETKEY )}, NULL },
{ "SAVETOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAVETOKEN )}, NULL },
{ "SAYDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAYDOWN )}, NULL },
{ "SAYMOVEIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAYMOVEIN )}, NULL },
{ "SAYSCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAYSCREEN )}, NULL },
{ "SAYSPREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SAYSPREAD )}, NULL },
{ "SCREENATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCREENATTR )}, NULL },
{ "SCREENFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCREENFILE )}, NULL },
{ "SCREENMARK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCREENMARK )}, NULL },
{ "SCREENMIX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCREENMIX )}, NULL },
{ "SCREENSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCREENSTR )}, NULL },
{ "SCREENTEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SCREENTEXT )}, NULL },
{ "SECTOTIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SECTOTIME )}, NULL },
{ "SETATLIKE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETATLIKE )}, NULL },
{ "SETBIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETBIT )}, NULL },
{ "SETCLEARA", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCLEARA )}, NULL },
{ "SETCLEARB", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETCLEARB )}, NULL },
{ "SETDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETDATE )}, NULL },
{ "SETFATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETFATTR )}, NULL },
{ "SETFCREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETFCREATE )}, NULL },
{ "SETFDATI", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETFDATI )}, NULL },
{ "SETFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETFONT )}, NULL },
{ "SETKXLAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETKXLAT )}, NULL },
{ "SETKXTAB", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETKXTAB )}, NULL },
{ "SETLASTKEY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETLASTKEY )}, NULL },
{ "SETPREC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPREC )}, NULL },
{ "SETRC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETRC )}, NULL },
{ "SETTIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETTIME )}, NULL },
{ "SHOWTIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SHOWTIME )}, NULL },
{ "SIGN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SIGN )}, NULL },
{ "SIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SIN )}, NULL },
{ "SINH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SINH )}, NULL },
{ "STANDARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( STANDARD )}, NULL },
{ "STRDIFF", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRDIFF )}, NULL },
{ "STRFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRFILE )}, NULL },
{ "STRSCREEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRSCREEN )}, NULL },
{ "STRSWAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( STRSWAP )}, NULL },
{ "TABEXPAND", {HB_FS_PUBLIC}, {HB_FUNCNAME( TABEXPAND )}, NULL },
{ "TABPACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( TABPACK )}, NULL },
{ "TAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( TAN )}, NULL },
{ "TANH", {HB_FS_PUBLIC}, {HB_FUNCNAME( TANH )}, NULL },
{ "TEMPFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( TEMPFILE )}, NULL },
{ "TIMETOSEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( TIMETOSEC )}, NULL },
{ "TIMEVALID", {HB_FS_PUBLIC}, {HB_FUNCNAME( TIMEVALID )}, NULL },
{ "TOKEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKEN )}, NULL },
{ "TOKENAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENAT )}, NULL },
{ "TOKENEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENEND )}, NULL },
{ "TOKENEXIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENEXIT )}, NULL },
{ "TOKENINIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENINIT )}, NULL },
{ "TOKENLOWER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENLOWER )}, NULL },
{ "TOKENNEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENNEXT )}, NULL },
{ "TOKENNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENNUM )}, NULL },
{ "TOKENSEP", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENSEP )}, NULL },
{ "TOKENUPPER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOKENUPPER )}, NULL },
{ "TOOLVER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOOLVER )}, NULL },
{ "TRUENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRUENAME )}, NULL },
{ "UNSELECTED", {HB_FS_PUBLIC}, {HB_FUNCNAME( UNSELECTED )}, NULL },
{ "UNTEXTWIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( UNTEXTWIN )}, NULL },
{ "VALPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALPOS )}, NULL },
{ "VGAPALETTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VGAPALETTE )}, NULL },
{ "VIDEOTYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VIDEOTYPE )}, NULL },
{ "VOLSERIAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VOLSERIAL )}, NULL },
{ "VOLUME", {HB_FS_PUBLIC}, {HB_FUNCNAME( VOLUME )}, NULL },
{ "WACLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WACLOSE )}, NULL },
{ "WAITPERIOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( WAITPERIOD )}, NULL },
{ "WALIAS", {HB_FS_PUBLIC}, {HB_FUNCNAME( WALIAS )}, NULL },
{ "WBOARD", {HB_FS_PUBLIC}, {HB_FUNCNAME( WBOARD )}, NULL },
{ "WBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( WBOX )}, NULL },
{ "WCENTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( WCENTER )}, NULL },
{ "WCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WCLOSE )}, NULL },
{ "WCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WCOL )}, NULL },
{ "WEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( WEEK )}, NULL },
{ "WFCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WFCOL )}, NULL },
{ "WFLASTCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WFLASTCOL )}, NULL },
{ "WFLASTROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WFLASTROW )}, NULL },
{ "WFORMAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WFORMAT )}, NULL },
{ "WFROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WFROW )}, NULL },
{ "WHIDE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WHIDE )}, NULL },
{ "WLASTCOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WLASTCOL )}, NULL },
{ "WLASTROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WLASTROW )}, NULL },
{ "WLEVEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WLEVEL )}, NULL },
{ "WLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( WLIST )}, NULL },
{ "WMODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WMODE )}, NULL },
{ "WMOVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WMOVE )}, NULL },
{ "WNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( WNUM )}, NULL },
{ "WOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( WOM )}, NULL },
{ "WOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( WOPEN )}, NULL },
{ "WORDONE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORDONE )}, NULL },
{ "WORDONLY", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORDONLY )}, NULL },
{ "WORDREM", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORDREM )}, NULL },
{ "WORDREPL", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORDREPL )}, NULL },
{ "WORDSWAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORDSWAP )}, NULL },
{ "WORDTOCHAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORDTOCHAR )}, NULL },
{ "WROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WROW )}, NULL },
{ "WSELECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( WSELECT )}, NULL },
{ "WSETMOVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( WSETMOVE )}, NULL },
{ "WSETSHADOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WSETSHADOW )}, NULL },
{ "WSHADOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WSHADOW )}, NULL },
{ "WSHOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( WSHOW )}, NULL },
{ "WSTEP", {HB_FS_PUBLIC}, {HB_FUNCNAME( WSTEP )}, NULL },
{ "XMOBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( XMOBLOCK )}, NULL },
{ "XMOCHECK", {HB_FS_PUBLIC}, {HB_FUNCNAME( XMOCHECK )}, NULL },
{ "XTOC", {HB_FS_PUBLIC}, {HB_FUNCNAME( XTOC )}, NULL },
{ "ZEROINSERT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ZEROINSERT )}, NULL },
{ "ZEROREMOVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ZEROREMOVE )}, NULL },
{ "_WSTACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( _WSTACK )}, NULL },
{ "__HBCT_DSPTIME", {HB_FS_PUBLIC}, {HB_FUNCNAME( __HBCT_DSPTIME )}, NULL },
{ "__HBCT_KEY_C_TO_N", {HB_FS_PUBLIC}, {HB_FUNCNAME( __HBCT_KEY_C_TO_N )}, NULL },
{ "__HBCT_KEY_N_TO_C", {HB_FS_PUBLIC}, {HB_FUNCNAME( __HBCT_KEY_N_TO_C )}, NULL },
{ "__HBEXTERN__HBCT__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBCT__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBCT, "..\\contrib\\hbct\\hbct.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBCT
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBCT )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBCT__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

