/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (32-bit)
 * Generated C source from "..\contrib\hbxpp\hbxpp.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( BIN2F );
HB_FUNC_EXTERN( BIN2U );
HB_FUNC_EXTERN( CONVTOANSICP );
HB_FUNC_EXTERN( CONVTOOEMCP );
HB_FUNC_EXTERN( CURDRIVE );
HB_FUNC_EXTERN( DBCOPYEXTSTRUCT );
HB_FUNC_EXTERN( DBCOPYSTRUCT );
HB_FUNC_EXTERN( DBJOIN );
HB_FUNC_EXTERN( DBLIST );
HB_FUNC_EXTERN( DBPACK );
HB_FUNC_EXTERN( DBRELEASE );
HB_FUNC_EXTERN( DBREQUEST );
HB_FUNC_EXTERN( DBSKIPPER );
HB_FUNC_EXTERN( DBSORT );
HB_FUNC_EXTERN( DBTOTAL );
HB_FUNC_EXTERN( DBUPDATE );
HB_FUNC_EXTERN( DBZAP );
HB_FUNC_EXTERN( DLLCALL );
HB_FUNC_EXTERN( DLLEXECUTECALL );
HB_FUNC_EXTERN( DLLLOAD );
HB_FUNC_EXTERN( DLLPREPARECALL );
HB_FUNC_EXTERN( DLLUNLOAD );
HB_FUNC_EXTERN( F2BIN );
HB_FUNC_EXTERN( NUMBUTTONS );
HB_FUNC_EXTERN( RUNSHELL );
HB_FUNC_EXTERN( SETMOUSE );
HB_FUNC_EXTERN( SIGNAL );
HB_FUNC_EXTERN( SLEEP );
HB_FUNC_EXTERN( THREAD );
HB_FUNC_EXTERN( THREADID );
HB_FUNC_EXTERN( THREADOBJECT );
HB_FUNC_EXTERN( THREADWAIT );
HB_FUNC_EXTERN( THREADWAITALL );
HB_FUNC_EXTERN( U2BIN );
HB_FUNC_EXTERN( W2BIN );
HB_FUNC_EXTERN( WORKSPACELIST );
HB_FUNC_EXTERN( XPP_DBUSEAREA );
HB_FUNC_EXTERN( XPP_GET );
HB_FUNC_EXTERN( XPP_INCLUDE );
HB_FUNC_EXTERN( XPP_INDEX );
HB_FUNC_EXTERN( XPP_OP_ARRAY );
HB_FUNC_EXTERN( XPP_OP_CHARACTER );
HB_FUNC_EXTERN( XPP_OP_OVERLOAD );
HB_FUNC_EXTERN( XPP_TBCOLUMN );
HB_FUNC_EXTERN( XPP_TBROWSE );
HB_FUNC_EXTERN( XPP_TBROWSEDB );
HB_FUNC_EXTERN( _DBEXPORT );
HB_FUNC_EXTERN( _TYPEFILE );
HB_FUNC( __HBEXTERN__HBXPP__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBXPP )
{ "BIN2F", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIN2F )}, NULL },
{ "BIN2U", {HB_FS_PUBLIC}, {HB_FUNCNAME( BIN2U )}, NULL },
{ "CONVTOANSICP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CONVTOANSICP )}, NULL },
{ "CONVTOOEMCP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CONVTOOEMCP )}, NULL },
{ "CURDRIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURDRIVE )}, NULL },
{ "DBCOPYEXTSTRUCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOPYEXTSTRUCT )}, NULL },
{ "DBCOPYSTRUCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOPYSTRUCT )}, NULL },
{ "DBJOIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBJOIN )}, NULL },
{ "DBLIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBLIST )}, NULL },
{ "DBPACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBPACK )}, NULL },
{ "DBRELEASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBRELEASE )}, NULL },
{ "DBREQUEST", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBREQUEST )}, NULL },
{ "DBSKIPPER", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSKIPPER )}, NULL },
{ "DBSORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSORT )}, NULL },
{ "DBTOTAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBTOTAL )}, NULL },
{ "DBUPDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUPDATE )}, NULL },
{ "DBZAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBZAP )}, NULL },
{ "DLLCALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DLLCALL )}, NULL },
{ "DLLEXECUTECALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DLLEXECUTECALL )}, NULL },
{ "DLLLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( DLLLOAD )}, NULL },
{ "DLLPREPARECALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DLLPREPARECALL )}, NULL },
{ "DLLUNLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( DLLUNLOAD )}, NULL },
{ "F2BIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( F2BIN )}, NULL },
{ "NUMBUTTONS", {HB_FS_PUBLIC}, {HB_FUNCNAME( NUMBUTTONS )}, NULL },
{ "RUNSHELL", {HB_FS_PUBLIC}, {HB_FUNCNAME( RUNSHELL )}, NULL },
{ "SETMOUSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETMOUSE )}, NULL },
{ "SIGNAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SIGNAL )}, NULL },
{ "SLEEP", {HB_FS_PUBLIC}, {HB_FUNCNAME( SLEEP )}, NULL },
{ "THREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREAD )}, NULL },
{ "THREADID", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADID )}, NULL },
{ "THREADOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADOBJECT )}, NULL },
{ "THREADWAIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADWAIT )}, NULL },
{ "THREADWAITALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( THREADWAITALL )}, NULL },
{ "U2BIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( U2BIN )}, NULL },
{ "W2BIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( W2BIN )}, NULL },
{ "WORKSPACELIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( WORKSPACELIST )}, NULL },
{ "XPP_DBUSEAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_DBUSEAREA )}, NULL },
{ "XPP_GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_GET )}, NULL },
{ "XPP_INCLUDE", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_INCLUDE )}, NULL },
{ "XPP_INDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_INDEX )}, NULL },
{ "XPP_OP_ARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_OP_ARRAY )}, NULL },
{ "XPP_OP_CHARACTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_OP_CHARACTER )}, NULL },
{ "XPP_OP_OVERLOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_OP_OVERLOAD )}, NULL },
{ "XPP_TBCOLUMN", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_TBCOLUMN )}, NULL },
{ "XPP_TBROWSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_TBROWSE )}, NULL },
{ "XPP_TBROWSEDB", {HB_FS_PUBLIC}, {HB_FUNCNAME( XPP_TBROWSEDB )}, NULL },
{ "_DBEXPORT", {HB_FS_PUBLIC}, {HB_FUNCNAME( _DBEXPORT )}, NULL },
{ "_TYPEFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( _TYPEFILE )}, NULL },
{ "__HBEXTERN__HBXPP__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBXPP__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBXPP, "..\\contrib\\hbxpp\\hbxpp.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBXPP
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBXPP )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBXPP__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

