/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (64-bit)
 * Generated C source from "rddbm\rddbm.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( BMDBFCDX );
HB_FUNC_EXTERN( BMDBFNSX );
HB_FUNC_EXTERN( BMDBFNTX );
HB_FUNC_EXTERN( BM_DBGETFILTERARRAY );
HB_FUNC_EXTERN( BM_DBSEEKWILD );
HB_FUNC_EXTERN( BM_DBSETFILTERARRAY );
HB_FUNC_EXTERN( BM_DBSETFILTERARRAYADD );
HB_FUNC_EXTERN( BM_DBSETFILTERARRAYDEL );
HB_FUNC_EXTERN( BM_TURBO );
HB_FUNC_EXTERN( _BMDBF );
HB_FUNC( __HBEXTERN__RDDBM__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_RDDBM )
{ "BMDBFCDX", {HB_FS_PUBLIC}, {HB_FUNCNAME( BMDBFCDX )}, NULL },
{ "BMDBFNSX", {HB_FS_PUBLIC}, {HB_FUNCNAME( BMDBFNSX )}, NULL },
{ "BMDBFNTX", {HB_FS_PUBLIC}, {HB_FUNCNAME( BMDBFNTX )}, NULL },
{ "BM_DBGETFILTERARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( BM_DBGETFILTERARRAY )}, NULL },
{ "BM_DBSEEKWILD", {HB_FS_PUBLIC}, {HB_FUNCNAME( BM_DBSEEKWILD )}, NULL },
{ "BM_DBSETFILTERARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( BM_DBSETFILTERARRAY )}, NULL },
{ "BM_DBSETFILTERARRAYADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( BM_DBSETFILTERARRAYADD )}, NULL },
{ "BM_DBSETFILTERARRAYDEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( BM_DBSETFILTERARRAYDEL )}, NULL },
{ "BM_TURBO", {HB_FS_PUBLIC}, {HB_FUNCNAME( BM_TURBO )}, NULL },
{ "_BMDBF", {HB_FS_PUBLIC}, {HB_FUNCNAME( _BMDBF )}, NULL },
{ "__HBEXTERN__RDDBM__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__RDDBM__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_RDDBM, "rddbm\\rddbm.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_RDDBM
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_RDDBM )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__RDDBM__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

