/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (64-bit)
 * Generated C source from "..\contrib\hbmzip\hbmzip.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_UNZIPCLOSE );
HB_FUNC_EXTERN( HB_UNZIPERRORSTR );
HB_FUNC_EXTERN( HB_UNZIPEXTRACTCURRENTFILE );
HB_FUNC_EXTERN( HB_UNZIPEXTRACTCURRENTFILETOHANDLE );
HB_FUNC_EXTERN( HB_UNZIPFILECLOSE );
HB_FUNC_EXTERN( HB_UNZIPFILEFIRST );
HB_FUNC_EXTERN( HB_UNZIPFILEGOTO );
HB_FUNC_EXTERN( HB_UNZIPFILEINFO );
HB_FUNC_EXTERN( HB_UNZIPFILENEXT );
HB_FUNC_EXTERN( HB_UNZIPFILEOPEN );
HB_FUNC_EXTERN( HB_UNZIPFILEPOS );
HB_FUNC_EXTERN( HB_UNZIPFILEREAD );
HB_FUNC_EXTERN( HB_UNZIPGLOBALINFO );
HB_FUNC_EXTERN( HB_UNZIPOPEN );
HB_FUNC_EXTERN( HB_ZIPCLOSE );
HB_FUNC_EXTERN( HB_ZIPDELETEFILE );
HB_FUNC_EXTERN( HB_ZIPERRORSTR );
HB_FUNC_EXTERN( HB_ZIPFILECLOSE );
HB_FUNC_EXTERN( HB_ZIPFILECRC32 );
HB_FUNC_EXTERN( HB_ZIPFILECREATE );
HB_FUNC_EXTERN( HB_ZIPFILEWRITE );
HB_FUNC_EXTERN( HB_ZIPOPEN );
HB_FUNC_EXTERN( HB_ZIPSTOREFILE );
HB_FUNC_EXTERN( HB_ZIPSTOREFILEHANDLE );
HB_FUNC( __HBEXTERN__HBMZIP__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBMZIP )
{ "HB_UNZIPCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPCLOSE )}, NULL },
{ "HB_UNZIPERRORSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPERRORSTR )}, NULL },
{ "HB_UNZIPEXTRACTCURRENTFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPEXTRACTCURRENTFILE )}, NULL },
{ "HB_UNZIPEXTRACTCURRENTFILETOHANDLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPEXTRACTCURRENTFILETOHANDLE )}, NULL },
{ "HB_UNZIPFILECLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILECLOSE )}, NULL },
{ "HB_UNZIPFILEFIRST", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEFIRST )}, NULL },
{ "HB_UNZIPFILEGOTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEGOTO )}, NULL },
{ "HB_UNZIPFILEINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEINFO )}, NULL },
{ "HB_UNZIPFILENEXT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILENEXT )}, NULL },
{ "HB_UNZIPFILEOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEOPEN )}, NULL },
{ "HB_UNZIPFILEPOS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEPOS )}, NULL },
{ "HB_UNZIPFILEREAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPFILEREAD )}, NULL },
{ "HB_UNZIPGLOBALINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPGLOBALINFO )}, NULL },
{ "HB_UNZIPOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_UNZIPOPEN )}, NULL },
{ "HB_ZIPCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPCLOSE )}, NULL },
{ "HB_ZIPDELETEFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPDELETEFILE )}, NULL },
{ "HB_ZIPERRORSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPERRORSTR )}, NULL },
{ "HB_ZIPFILECLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILECLOSE )}, NULL },
{ "HB_ZIPFILECRC32", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILECRC32 )}, NULL },
{ "HB_ZIPFILECREATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILECREATE )}, NULL },
{ "HB_ZIPFILEWRITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPFILEWRITE )}, NULL },
{ "HB_ZIPOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPOPEN )}, NULL },
{ "HB_ZIPSTOREFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPSTOREFILE )}, NULL },
{ "HB_ZIPSTOREFILEHANDLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_ZIPSTOREFILEHANDLE )}, NULL },
{ "__HBEXTERN__HBMZIP__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBMZIP__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBMZIP, "..\\contrib\\hbmzip\\hbmzip.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBMZIP
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBMZIP )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBMZIP__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

