/*
 * Harbour 3.2.0dev (r2004201301)
 * Microsoft Visual C 19.25.28614 (32-bit)
 * Generated C source from "hbmlzo\hbmlzo.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_LZO1X_1_COMPRESS );
HB_FUNC_EXTERN( HB_LZO1X_DECOMPRESS );
HB_FUNC_EXTERN( HB_LZO1X_DECOMPRESS_SAFE );
HB_FUNC_EXTERN( HB_LZO_COMPRESSBOUND );
HB_FUNC_EXTERN( LZO_ADLER32 );
HB_FUNC_EXTERN( LZO_VERSION );
HB_FUNC_EXTERN( LZO_VERSION_DATE );
HB_FUNC_EXTERN( LZO_VERSION_STRING );
HB_FUNC( __HBEXTERN__HBMLZO__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBMLZO )
{ "HB_LZO1X_1_COMPRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LZO1X_1_COMPRESS )}, NULL },
{ "HB_LZO1X_DECOMPRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LZO1X_DECOMPRESS )}, NULL },
{ "HB_LZO1X_DECOMPRESS_SAFE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LZO1X_DECOMPRESS_SAFE )}, NULL },
{ "HB_LZO_COMPRESSBOUND", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_LZO_COMPRESSBOUND )}, NULL },
{ "LZO_ADLER32", {HB_FS_PUBLIC}, {HB_FUNCNAME( LZO_ADLER32 )}, NULL },
{ "LZO_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( LZO_VERSION )}, NULL },
{ "LZO_VERSION_DATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( LZO_VERSION_DATE )}, NULL },
{ "LZO_VERSION_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( LZO_VERSION_STRING )}, NULL },
{ "__HBEXTERN__HBMLZO__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBMLZO__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBMLZO, "hbmlzo\\hbmlzo.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBMLZO
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBMLZO )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBMLZO__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

